### ISSUE TITLE
C4EI want add https://chainlist.org/ please help !!

### ISSUE THREAD

**Issue by c4ei** [ethereum-lists/chains#1000]
{
  "name": "C4EI Mainnet",
  "chain": "C4EI",
  "network": "C4EI Mainnet",
  "icon": "c4ei",
  "rpc": [
    "https://rpc.c4ei.net"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "C4EI",
    "symbol": "C4EI",
    "decimals": 18
  },
  "infoURL": "https://c4ei.net",
  "shortName": "c4ei",
  "chainId": 21004,
  "networkId": 21004
}

**Comment by ggbbest** [comment]
today added below file can you confirm?

https://github.com/ethereum-lists/chains/tree/master/_data/chains/eip155-21004.json
https://github.com/ethereum-lists/chains/tree/master/_data/icons/c4ei.json
https://github.com/DefiLlama/chainlist/blob/main/utils/extraRpcs.json  --> C4EI Added

**Comment by ggbbest** [comment]
--> i found change file below...
https://github.com/ggbbest/chains/blob/master/_data/chains/eip155-21004.json
https://github.com/ggbbest/chains/blob/master/_data/icons/c4ei.json

**Comment by ggbbest** [comment]
i want add https://github.com/DefiLlama/chainlist/blob/main/utils/extraRpcs.json file below line
,
    "21004": {
        "rpcs":[
            "https://rpc.c4ei.net"
        ]
    }
