### ISSUE TITLE
Adding Shardeum Test Net

### ISSUE THREAD

**Issue by simba-sandy** [ethereum-lists/chains#1115]
https://docs.shardeum.org/basics/endpoints

Network Name | Shardeum Liberty 1.0
New RPC URL | https://liberty10.shardeum.org/
Chain ID | 8080
Currency symbol (optional) | SHM
Block Explorer URL (optional) | http://explorer.liberty10.shardeum.org:5555/

**Comment by ligi** [comment]
8080 is already used: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-8080.json
