### ISSUE TITLE
Private/Incubating chains 

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#1144]
came up in #1142 

Maybe we should have a boolean field "private" - so they can be filtered out in sites like https://chainid.network
In this process we could also introduce "incubating" for the case people want to reserve chainIDs before they go public

Would that work for everyone? Are bools here enough? Is this future compatible? How can we prevent squatting of chainIDs?
E.g. I think nice chainID numbers should never be granted for private chains.
Input on all this is most welcome!

**Comment by pangzheng** [comment]
The purpose of chainID itself is to prevent replay attack, it is not an independent resource.

The chainid should not be divided into public and private, the private network transaction ChainID conflicts, there is still the risk of replay attack

**Comment by likai1130** [comment]
understand that alliance chains and private networks may have this demand.
In addition, the modification of chainid is set when the chain is created. The modification leads to the reproduction of the whole chain. The cost is a little high.
For the problem that chainid has been registered, a specification can be issued to specify the application requirements.

**Comment by Jopnrn** [comment]
Cancelar

Em seg., 9 de mai. de 2022 às 06:10, likai1130 ***@***.***>
escreveu:

**Comment by ligi** [comment]
> maybe private/Incubating chain should move to the candidates list, not to the public list

it kinda becomes a different list with the new fields - but makes it easier than having separate lists

> The purpose of chainID itself is to prevent replay attack, it is not an independent resource.
> 
> The chainid should not be divided into public and private, the private network transaction ChainID conflicts, there is still the risk of replay attack

the list here has multiple purposes though - one purpose is to coordinate on chainIDs - but another one is public listing of chains like with https://chainlist.network - and there it does not make sense to list private chains

**Comment by Jopnrn** [comment]
Cancelar

Em qua., 11 de mai. de 2022 às 09:15, ligi ***@***.***>
escreveu:

**Comment by pangzheng** [comment]
> So far I think we should just add a `status` field which can be `incubating`, `private`, `active` `deprecated` - I think this is the most flexible solution

this think so cool

**Comment by raulk** [comment]
Hey! This is Raúl from the Filecoin Project. We are looking to reserve a chain ID for the Filecoin EVM runtime. Our Ethereum JSON-RPCs are under construction, but should ship in the next weeks. Is there a way we could make a submission in anticipation of JSON-RPC and chain explorer support?

**Comment by ligi** [comment]
you can add "status":"incubating" to the chains - it is supported - just forgot to close the issue
