### ISSUE TITLE
Chain ID conflict

### ISSUE THREAD

**Issue by moumc** [ethereum-lists/chains#1150]
Sorry, only found out about this site now. Our mainnet chain ID already exists in the chainlist, but today our mainnet has been running stably for 294 days, how can I submit information to the chainlist? Please guide me.

**Comment by ligi** [comment]
I tried contacting them: https://twitter.com/mr_ligi/status/1524647555170250753
We need to wait a bit for them to respond. 
Or if you can prove their chain is not older - we can make it faster.

**Comment by moumc** [comment]
My company's mainnet rpc:  http://walletrpc.aitd.io and browser:  https://aitd-explorer.aitd.io/ , and chain id is 19

**Comment by ligi** [comment]
yea - seems your chain is a bit older. 
ccIng @sprwn-zz @RareData
Will still give them some time to respond - but you can prepare the PR replacing the chain already. The older chain wins.

**Comment by RareData** [comment]
We publicly communicated our use of chain ID 19 **before** AITD launched and began integrations of Songbird into firmware from Trezor and Ledger, as well as observed numerous custody providers and exchanges complete integrations using our reserved chain ID.

Ethereum Lists PR **(2021-07-21)**
https://github.com/ethereum-lists/chains/pull/346

Trezor Firmware (2021-08-24)
https://github.com/trezor/trezor-firmware/blame/master/core/src/apps/ethereum/networks.py#L172

Ledger Firmware (2021-08-05)
https://github.com/LedgerHQ/app-ethereum/blame/4b55157c3e27fa291954f9a3e060a41ca193e2e9/Makefile#L231

There are numerous active integrations of Songbird (SGB) including trading on at least Bitstamp, Gate.io, Bitrue, Kraken, MEXC and Bitfinex. There are numerous active integrations of Songbird (SGB) using chain ID 19 with custody providers including at least [Fireblocks](https://www.fireblocks.com/blog/songbird-x-fireblocks/) and HexTrust.

Your blockchain explorer's first record on Wayback Machine is from 2022-02-18 https://web.archive.org/web/20220218174209/https://aitd-explorer.aitd.io/ while ours is from 2021-09-17 https://web.archive.org/web/20210917195040/https://songbird-explorer.flare.network/

**Comment by ligi** [comment]
In that case I would lean to keep your chain in the list - but will wait for @moumc to respond
