### ISSUE TITLE
Icon display issue

### ISSUE THREAD

**Issue by mmtchain1** [ethereum-lists/chains#1151]
I commit a pull request (https://github.com/ethereum-lists/chains/pull/1129) and it has merged. But the icon of the chain doesn't display on the webpage (https://chainlist.org/), Please tell me what else I need to do to make it correct, thanks.
<img width="942" alt="截屏2022-05-12 22 36 39" src="https://user-images.githubusercontent.com/99935237/168101311-bed81596-5d62-40ef-af41-ae3d7f7bc4f2.png">

**Comment by ligi** [comment]
You need to open an issue there - not here.
