### ISSUE TITLE
Request: Publish as npm package

### ISSUE THREAD

**Issue by rekmarks** [ethereum-lists/chains#116]
For consumers of `chains.json` that don't want to query the chainId.network website, it'd be nice if `chains.json` were published as an npm package. I'd be happy to help maintain the package if that would be helpful.

**Comment by pedrouid** [comment]
It already exists but it currently queries this repository in runtime. We should refactor it to include the JSON in the build instead

https://github.com/pedrouid/evm-chains

**Comment by ligi** [comment]
maybe we should mention this npm package in the readme and/or the chainid.network website. I was also not aware of it. I am happy something like this exists - but really want to stay as far away as possible from js/npm stuff - so really happy that someone else maintains it ;-)

**Comment by pedrouid** [comment]
I've updated the package to include the latest state of this registry and made all methods synchronous 👌 

https://www.npmjs.com/package/evm-chains

**Comment by pedrouid** [comment]
Don't worry @ligi 😝 I will always be there to maintain ugly ducky js/npm when needed

**Comment by rekmarks** [comment]
Awesome, thanks guys!

**Comment by paulrberg** [comment]
Looks like the `evm-chains` package hasn't been updated since November 2020.

We should create a GitHub workflow that automatically published a new npm package on every change made in this repository.
