### ISSUE TITLE
Auxilium chain causing problems on Windows

### ISSUE THREAD

**Issue by matejcik** [ethereum-lists/chains#118]
In https://github.com/ethereum-lists/chains/blob/16fcf0dbb5c47534fdb5766ba4ad9f45d8534a65/_data/chains/28945486.json#L15 the Auxilium chain uses short name `aux`.
This is a [reserved file name](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) on Windows. I'm not sure if it's a problem when it is a directory (if we ever add Auxilium tokens, the tokens repo will need to get a `aux` subdir), but it is definitely a problem with a file.

We ran into this when storing icons as `<shortName>.png`

If it's OK, I propose changing the shortName to `auxi`

**Comment by ligi** [comment]
I would be ok with the change - but do not yet understand where the problem comes from (don't use windows)

**Comment by matejcik** [comment]
where it _comes from_ is ancient history. how it manifests is you can't create file named `aux` or `aux.*`. Meaning that, e.g., it would be impossible to check out a repository with `aux` directory on Windows.

I'll make a PR then

**Comment by ligi** [comment]
wonder if another fix could be to change the icon naming like <shortName>_icon.png
