### ISSUE TITLE
Is there api for chain icon?

### ISSUE THREAD

**Issue by jadeydi** [ethereum-lists/chains#1186]

**Comment by ligi** [comment]
what do you mean with API in this context?

**Comment by jadeydi** [comment]
{
name: "Ethereum Mainnet",
chain: "ETH",
icon: "ethereum",
}

the icon in the response body of the chain is a name, how can I get the chain's icon through api? Here are the icons of chains https://github.com/ethereum-lists/chains/tree/master/_data/icons

**Comment by ligi** [comment]
closed via f761550d62be4f2c4ef45fba5717d530f92844e1
You can now e.g. get https://chainid.network/icons/ethereum.json
all files from _data are available. 

Is this what you had in mind?
