### ISSUE TITLE
UNISWAP ETH/SHINJA PAIR NEEDS TO UPDATE 

### ISSUE THREAD

**Issue by redemptorridon** [ethereum-lists/chains#1193]
The pair for UNISWAP ETH/SHINJA PAIR needs to be updated in ETHERSCAN by contract owner. 

[UNISWAP PAIR](https://etherscan.io/token/0x63b61e73d3fa1fb96d51ce457cabe89fffa7a1f1) 

IT CURRENTLY "TOKEN Uniswap V2" - IT HAS TO BE ETH/SHINJA or SHINJA/ETH

**Comment by ligi** [comment]
seems like the wrong repo for that
