### ISSUE TITLE
Add RPC endpoints

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#12]
wonder if we should add a list of RPC endpoints (can also be an empty list - so the field is optional) for the chains.
Inspired by https://github.com/ethereum-lists/chains/pull/10#issuecomment-454411114

This would also allow a ci-script to make checks for the chain_id (also inspired by the very same PR)

Disadvantage might be that it is widening the scope too much - what does the rest of the team think?

**Comment by bmann** [comment]
Chatted to @ligi about this. Let’s add valuable per chain data if we have data for a number of chains. Let’s learn what’s most useful and go from there.

**Comment by ligi** [comment]
Moving from question to enhancement as I see rough consensus here

**Comment by saurik** [comment]
Can this list also include ws/wss endpoints in addition to http/https endpoints, or would you want that in a different key?

**Comment by ligi** [comment]
Good question. I would say yes as it seems to be the most clean solution. But I am not 100% sure if all consuming parties can deal with it (meaning e.g. ignore these entries if wss is not supported). I will try to reach out to some people. Where do you want to add them currently?

**Comment by saurik** [comment]
@ligi By "where" do you mean "for which chains" or "where in the schema"? I know of public websocket endpoints for at least POA, xDai, and Binance Smart Chain; and, since Infura API keys are allowed as parameters, Ethereum. (As for the schema, I personally felt they should go in the same list as the http endpoints, and that is where I was putting them in the little database of chains I was momentarily putting together yesterday, before my research led me to this shared resource; but I don't actually "care", which is why I asked where you all felt they should go ;P.)

**Comment by ligi** [comment]
@saurik great! yea with "where" I mean which chains.
I think just go ahead with it. Thought about it a bit more and there was never actually a guarantee that these are only http(s) addresses. Was just the case by chance until now. IMHO it is totally valid to also add wss:// URLs

**Comment by nicexe** [comment]
I'm not sure what the purpose of adding RPC endpoints serves.
If you connect a node to a network, you have your own RPC endpoint at http://127.0.0.1:8545 or ws://127.0.0.1:8546
Maybe there is something that I'm not getting here.

**Comment by ligi** [comment]
this is about public endpoints. Not always you have access to a local endpoint

**Comment by minimayki6232** [comment]
> wonder if we should add a list of RPC endpoints (can also be an empty list - so the field is optional) for the chains.
> Inspired by https://github.com/ethereum-lists/chains/pull/10#issuecomment-454411114
> 
> This would also allow a ci-script to make checks for the chain_id (also inspired by the very same PR)
> 
> Disadvantage might be that it is widening the scope too much - what does the rest of the team think?

**Comment by minimayki6232** [comment]
> Chatted to @ligi about this. Let’s add valuable per chain data if we have data for a number of chains. Let’s learn what’s most useful and go from there.
