### ISSUE TITLE
Dear ethereum-lists, please be aware: Echelon chain is scam

### ISSUE THREAD

**Issue by alpha-omega-labs** [ethereum-lists/chains#1216]
Please, be aware, Echelon chain is a scam, According to blockchain analysis organization launched echelon 100% control consensus by controlling >67% of coins, pretending its decentralized. Echelon is spam, scam, pump and dump.

**Comment by ligi** [comment]
yea - also had a bad feeling with them - see #1096

**Comment by ligi** [comment]
Maybe I just revert it to the testnet or add a big red warning flag

**Comment by alpha-omega-labs** [comment]
u r awesome! 
If you will have time take a look at GenesisL1 and molnft.io and take some L1 (gift, free, valueless, utility) for any needs or fun. 
P.S. Can mint molecular structure with it!

**Comment by echelonfoundation** [comment]
> Please, be aware, Echelon chain is a scam, According to blockchain analysis organization launched echelon 100% control consensus by controlling >67% of coins, pretending its decentralized. Echelon is spam, scam, pump and dump.

You can view the public community blockchain network explorers at https://ping.pub/echelon and https://scout.ech.network

There is around ~190,000,000 ECH in circulation, which is transparently known. We encourage you to join our Discord at https://discord.gg/echelon and actually do some research before making false accusations, with zero proof.

Our codebase is open source and audited at https://github.com/echelonfoundation/echelon

Funny how this person opens some fake issue claiming an open source blockchain network with a custom bridge is a scam just to shill his own scam.

**Comment by echelonfoundation** [comment]
We have already reported this user @alpha-omega-labs to Github several times for spamming, attacking, and harassing us. He previously opened a bunch of non-sense issues on our Github. They are investigating him at this time.

**Comment by ligi** [comment]
@echelonfoundation 

none of your points refute: 
> echelon 100% control consensus by controlling >67% of coins

@alpha-omega-labs 

can you give a link to 
>  According to blockchain analysis organization

**Comment by echelonfoundation** [comment]
This issue has been reported to Github staff again.



> @echelonfoundation
> 
> none of your points refute:
> 
> > echelon 100% control consensus by controlling >67% of coins
> 
> @alpha-omega-labs
> 
> can you give a link to
> 
> > According to blockchain analysis organization

You can join our community https://discord.gg/echelon and find answers to all of these questions or ask anyone in the community.

We stealth launched on seven blockchains and our chain around just over a month ago, there is ~45/100 active validators on chain: https://app.ech.network/validators

There are community pool funds that can be proposed on chain and around ~50,000,000 ECH in developer incentives at this time that the Echelon Team controls. https://ech.network/incentives

There are two on-chain EVM DEXs at https://echswap.finance and https://defyswap.finance they are community ran. There is bECH (Bridged Echelon) which is 1 to 1 pegged/redeemable for native ECH on the seven L1 EVM blockchains on their popular DEXs. Echelon is also listed on IndoEX, ZT Global, and Coinsbit.

Our official auditor partner is https://kishield.com they provide reasonably priced audits for any tokens or projects deploying on chain, which they also had audited bECH (Bridged Echelon) https://github.com/KISHIELD/Audits/blob/main/KISHIELD_BridgedECH_Audit_20220420.pdf

**Comment by ligi** [comment]
Again - none of your points refute:
> echelon 100% control consensus by controlling >67% of coins

And I really have no interest joining your discord.
I will wait for the link from @alpha-omega-labs

**Comment by ligi** [comment]
And ROFL at the "audit" - hope this was never printed - would not be worth the paper it would have been printed on ..

**Comment by echelonfoundation** [comment]
> Again - none of your points refute:
> 
> > echelon 100% control consensus by controlling >67% of coins
> 
> And I really have no interest joining your discord. I will wait for the link from @alpha-omega-labs

You can easily verify that is not true by joining our Discord to see the community yourself and to be able to talk to other Echelon holders.

You can also easily verify coin holders by checking the explorers on each blockchain for bECH and also by checking the validators list, linked above, etc. There are many ways to verify we are indeed telling you the truth.

**Comment by echelonfoundation** [comment]
> 

It was only needed initially to build trust and give a general explanation of how the Bridged Echelon token works. It fulfills the prior need for the contract to be audited.

**Comment by ligi** [comment]
> There are many ways to verify we are indeed telling you the truth.

So far what you are saying does not even make sense or addresses the concern of @alpha-omega-labs - I will wait for the link and go from there.

**Comment by ligi** [comment]
You seem to really have no clue what you are talking about. How can I know that these are not entities controlled by you? That's why I wait for the link from the blockchain analysis organization and do not look at your explorers or discord (which makes no sense at all)

**Comment by echelonfoundation** [comment]
> You seem to really have no clue what you are talking about. How can I know that these are not entities controlled by you? That's why I wait for the link from the blockchain analysis organization and do not look at your explorers or discord (which makes no sense at all)

That is why we said go join the Discord and see for yourself the community and ecosystem. You could tag a validator and verify they are whom they are. Most validators get tagged with the Validator role there.

Ping.pub runs the main https://ping.pub explorer for many Cosmos based blockchains. (Our top validator with the most delegated)

**Comment by echelonfoundation** [comment]
> You seem to really have no clue what you are talking about. How can I know that these are not entities controlled by you? That's why I wait for the link from the blockchain analysis organization and do not look at your explorers or discord (which makes no sense at all)

You might be waiting a long time, because there is no link or blockchain analysis organization.

**Comment by Iigi** [comment]
After further research I found out there is no such blockchain analysis organization and you are correct in your findings that I do indeed have no clue what I am doing.

After even further analysis I was able to deduce that in fact Alpha Omega Labs and their Genesis L1 project is spam, scam, and a pump and dump. I would highly recommend that no one click on any links from Alpha Omega Labs and or Genesis L1.

My deepest apologies to you and the Echelon community for being rude to the Echelon team and I hope for their kind understandings, I was not expecting to be exposed for being a lazy troll and I agree I am doing a poor job representing the Ethereum community.

> > You seem to really have no clue what you are talking about. How can I know that these are not entities controlled by you? That's why I wait for the link from the blockchain analysis organization and do not look at your explorers or discord (which makes no sense at all)
> 
> You might be waiting a long time, because there is no link or blockchain analysis organization. It makes plenty of sense to review explorers and Discord, that is one of the #1 ways to validate what is going on within a blockchain.

**Comment by echelonfoundation** [comment]
@ligi We have given you no reason to claim we are a scam, as you slander our hard work. All you are doing at this point is defamation, you could spend 1 minute doing a tiny bit of work you would see we are a legit blockchain. 

Have you even clicked the link for "Genesis L1" posted above by @alpha-omega-labs which you are clearly a bias fan of? Their website screams shit token/scam.

> After further research I found out there is no such blockchain analysis organization and you are correct in your findings that I do indeed have no clue what I am doing.
> 
> After even further analysis I was able to deduce that in fact Alpha Omega Labs and their Genesis L1 project is spam, scam, and a pump and dump. I would highly recommend that no one click on any links from Alpha Omega Labs and or Genesis L1.
> 
> My deepest apologies to you and the Echelon community for being rude to the Echelon team and I hope for their kind understandings, I was not expecting to be exposed for being a lazy troll and I agree I am doing a poor job representing the Ethereum community.
> 
> > > You seem to really have no clue what you are talking about. How can I know that these are not entities controlled by you? That's why I wait for the link from the blockchain analysis organization and do not look at your explorers or discord (which makes no sense at all)
> > 
> > 
> > You might be waiting a long time, because there is no link or blockchain analysis organization. It makes plenty of sense to review explorers and Discord, that is one of the #1 ways to validate what is going on within a blockchain.

Thank you so much also and so sorry for our rude remarks as well, very frustrating dealing with this guy trying to FUD our project. Hopefully you can report also to Github, might give them a boost on the reports sent. Cheers!

**Comment by ligi** [comment]
I will report creating https://github.com/Iigi to github - if it was done by your IP @echelonfoundation - you are in big trouble

**Comment by echelonfoundation** [comment]
> I will report creating https://github.com/Iigi to github - if it was done by your IP @echelonfoundation - you are in big trouble

Was not us, we noticed last second above when going between the repositories and our discussion. 

Why are there people impersonating you and commenting on this issue pretending to be you? Why was this issue opened randomly with zero proof and tagged in the main PR? Why are you refusing to do basic blockchain research?

**Comment by echelonfoundation** [comment]
Why are you removing our comments? Our comments contain our rebuttal to this issue and proof?

**Comment by ligi** [comment]
> Why are you removing our comments? Our comments contain our rebuttal to this issue and proof?

because it was quoting "Iigi" - which was not me - with this fake content.
The user is deleted now - but that does not mean the traces are gone - it is still in githubs database - and if it is the same IP as you are logged in from you will be in big trouble.
Also there was no proof at all in the comment.

> Why are there people impersonating you and commenting on this issue pretending to be you? 

good question - I will find out - but so far it looks to me as if it was you

> Why are you refusing to do basic blockchain research?

Because the "research" you suggest makes no sense - if @alpha-omega-labs provides a link I will read it and do research afterwards based on this information.

**Comment by echelonfoundation** [comment]
We reported this entire thread to Github including the troll accounts @ligi and @alpha-omega-labs which are clearly working together to attack and harass our project. At this point it is just slander and defamation, you have both been given information to resolve your question/issue above, the issue can be closed easily and all information and questions answered and verified.

![image](https://user-images.githubusercontent.com/102999403/171966799-3dccfdae-85d0-4e2e-9566-b08743a76d13.png)

This is a screenshot of part of the comment deleted above, which apparently this was a imposter pretending to actually review this issue??

You can actually be the one in big trouble @ligi if you continue to harass us. You are clearly trolling and harassing our project, would be possible that you are also @alpha-omega-labs, which Github will be able to also confirm. We have provided you everything you need to do trustless verification of the data.

**Comment by echelonfoundation** [comment]
> Because the "research" you suggest makes no sense - if @alpha-omega-labs provides a link I will read it and do research afterwards based on this information.

@ligi Explain to us how that makes no sense to do BASIC blockchain research by checking the available explorers, validator list, and communities to verify. You do not make sense and are clearly a troll working with @alpha-omega-labs

**Comment by ligi** [comment]
Chain is removed - user is blocked

**Comment by ligi** [comment]
Background: Their behavior was just unacceptable - I deleted a post of my imposter - then they posted a screenshot of that. I really had enough of their behavior.

**Comment by alpha-omega-labs** [comment]
omg
Its very pity that there is a need to waste time on this, yet this issue could not not be raised because of moral obligation and to keep our common current and future web3 blockchain home clean, and better say self clean!

It also very hard to explain why black is black and why 2*2=4.
Yet.
Echelon blockchain appeared out nowhere in about mid April 2022, being a pure fork of Evmos (ethermint) and never mentioned this nowhere (besides all code says it). Repo is made and "promoted" as own source code. This chain, never known to anyone in any cosmos or evmos community also appear with index -4, meaning that there should be 3 chains versions before this. But no.
This chain also appeared in VERY shady initial part of coin distribution, conducted "privately" within a very short period of time.
This chain also appeared immediately with a validators set of >20 validators all with same setup.
This chain also appeared immediately with claim in their docs that there is 1,000,000 coins recommended to be validator. While in Cosmos SDK its 1 coin unit enough to be validator in their setup. 
This chain also, being out of nowhere had such patterns as: bot/script (fake) transactions on chain and fake addresses and activity creation in the very first days/weeks of chain life, for example appearance of 3000-14000 registered addresses within a short (hours) period of time. 
Echelon also pretend to be focusing on bridges, and pretend bridges are self made. Its not open sourced, and seems to be chainsafe bridges, but nor open sourced, nor linked to source.
This chain also have social media accounts (telegram, twitter) full of bots and trolls and this "inu" tokens patterns, all happened within short period of time and is similar to "inu" and other ERC-20 scam token patterns. (basically all same)
With all mentioned (closed source bridges to all chains, visible consensus control by deployer) echelon promote bridging stablecoins to own chain.  
Meanwhile, echelon has geth rpc open in their handy botnet validators nodes storing millions of tokens sent from main distribution account. 
----
ping.pub is a greatest project! and ping poses project as entirely open source, and basically have no entrance policy, so all new cosmos chains added there. 
You can dm in our project lounge (I don't even wanna name it in topic) for more deep explanation.
Thank you
