### ISSUE TITLE
On site https://chainlist.org/ Still not found

### ISSUE THREAD

**Issue by cppfuns** [ethereum-lists/chains#1260]
The submitted additions have been merged and it has been 2 days since they were added on the website https://chainlist.org/ Still not found

https://github.com/ethereum-lists/chains/commit/6d959b87c557cf770837fa94c5f12b617fa3beb7

**Comment by cppfuns** [comment]
@ligi website https://chainlist.org/ What is the refresh interval? Or is there a technical problem?

**Comment by Midkddksk** [comment]
Buenas noches m podrían ayudar a pasar todos estos datos a sus respectivas
billeteras ya que no se cómo hacerlo gracias

**Comment by ligi** [comment]
Please ask @/DefiLlama - this repo is not about that UI

**Comment by cppfuns** [comment]
@ealdealshaman

**Comment by cppfuns** [comment]
@realdealshama

**Comment by hobbydev71** [comment]
@cppfuns , now is your chain is listed on https://chainlist.org/?
Is other action needed to list the chain?

**Comment by zaksta11** [comment]
I still got modified repository..don't no WHT am doing bt learning

**Comment by zaksta11** [comment]
It hacked alot bye accident..branch master of 3 weeks..
