### ISSUE TITLE
Use CAIP-2 as filename

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#130]
currently we use EIP-155 for the filename - but this can lead to collisions (or better a problem adding chains) as @matejcik pointed out here: https://twitter.com/yangWao/status/1330871940534448128

A solution can be to use CAIP-2 as basis for the filename

Please veto now if you see problems ahead with this!

cc @pedrouid @bmann

**Comment by pedrouid** [comment]
Actually I think this is a great decision because I believe it also solves our chain sorting issue right?

**Comment by pedrouid** [comment]
Doesn't look like it fixes the sorting issue either as observed [here](https://github.com/ethereum-lists/chains/tree/pedrouid/caip2-filename/_data/chains)
