### ISSUE TITLE
Add chain reference resolvers to CAIP-2 namespaces

### ISSUE THREAD

**Issue by pedrouid** [ethereum-lists/chains#135]
This has been previously discussed and something that should be done asap

CAIP-2 should require namespaces to reference how to resolve chain references from its node endpoints

**Comment by ligi** [comment]
guess this one is in the wrong repo?

**Comment by pedrouid** [comment]
Wow I'm surprised I didn't notice this until you commented 😅 Can you transfer it to [ChainAgnostic/CAIPs](https://github.com/ChainAgnostic/CAIPs/)?

**Comment by ligi** [comment]
unfortunately a cross-org move does not seem to be possible. So did it manually

moved to https://github.com/ChainAgnostic/CAIPs/issues/41
