### ISSUE TITLE
Native asset names on several testnets are incorrect

### ISSUE THREAD

**Issue by vmichalik** [ethereum-lists/chains#1414]
**Problem**
Native assets on several testnets are incorrect compared to the canonical faucets and developer documentation available.

Arbitrum Rinkeby [docs](https://developer.offchainlabs.com/docs/public_chains) = RinkebyETH
[This repo](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-421611.json) = ARETH

Optimism Kovan [docs](https://community.optimism.io/docs/useful-tools/faucets/#goerli-faucet) = ETH
[This repo](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-69.json) = KOR

Goerli Github [PRs and Issues](https://github.com/eth-clients/goerli) = ETH
[This repo](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-5.json) = GOR

Ropsten in all other interfaces e.g. [Etherscan](https://ropsten.etherscan.io/), [Faucet](https://faucet.paradigm.xyz/) = ETH 
[This repo](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-3.json) = ROP

Rinkeby in all other interfaces as above = ETH 
[This repo](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-4.json) = RIN

Kovan in all other interfaces as above and e.g. [Infura](https://docs.infura.io/infura/networks/optimism/how-to/get-some-testnet-eth) = ETH
[This repo](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-42.json) = KOV

**Solution**

I would propose to change all the above native assets to their more commonly accepted names as above.
I couldn't find any more guidance on why new native token names were invented here?

**Comment by ligi** [comment]
> I would propose to change all the above native assets to their more commonly accepted names as above.

please make a PR changing this

> I couldn't find any more guidance on why new native token names were invented here?

I can check when there are PRs with changes to names if it is legit - but cannot check for every interaction - maybe there where also renames - there is no reason or invented here

**Comment by vmichalik** [comment]
Added #1415, thanks for the quick response @ligi

**Comment by ligi** [comment]
thanks for caring about consistency!

**Comment by vmichalik** [comment]
likewise thanks for the quick turnaround and for maintaining this valuable resource!
