### ISSUE TITLE
Publish as an NPM module

### ISSUE THREAD

**Issue by DefiDebauchery** [ethereum-lists/chains#1431]
I had posed [an idea](https://github.com/ensdomains/address-encoder/issues/349) to ENS to utilize `ethereum-lists` to power the list of networks on domain address fields, instead of their internal (duplicated) structure.

While they are willing to adopt, they'd (understandably) prefer it as an inline dependency versus external endpoint. Publishing as an NPM module may assist other projects in more easily referencing the chain list, as well.

**Comment by ligi** [comment]
This is a good idea - but I am not in the npm/js space - so if anyone could help with this it would be great!

**Comment by ashutoshpw** [comment]
@ligi I can take this up.

**Comment by DefiDebauchery** [comment]
Hi @ashutoshpw, have you been able to make any progress towards turning this into an npm library? 🙏

**Comment by ashutoshpw** [comment]
@DefiDebauchery Yes, as of now it can be accessed from [here](https://github.com/W3Dev/ethereum-lists/pkgs/npm/ethereum-lists) or from [here](https://www.npmjs.com/package/ethereum-lists). I will be adding more functionality over there by next month.

**Comment by DefiDebauchery** [comment]
Thanks for taking the time to do that. Perhaps you can work with @ligi to publish under the ethereum-lists namespace?

**Comment by ashutoshpw** [comment]
I want the package to be bit matured before we actually recognize it officially.

**Comment by cassa72** [comment]
Done

**Comment by DefiDebauchery** [comment]
> Done

Doesn't appear to be. Last release from Ashutosh was 2 months ago, and I don't see any mention of a package owned by ethereum-lists

**Comment by rickmark** [comment]
Feel free to shamelessly steal from where we do something very much like this (data files that get shipped to NPM, PyPI and Gems):

https://github.com/hack-different/apple-knowledge/tree/main/_packages

**Comment by AlicanC** [comment]
Just opened a PR that would make the repo installable: https://github.com/ethereum-lists/chains/pull/6592

This isn't as good as setting up CI to publish actual packages to NPM but it's better than nothing.
