### ISSUE TITLE
Adding attribute field for Testnets

### ISSUE THREAD

**Issue by DefiDebauchery** [ethereum-lists/chains#1432]
While it can often be inferred by the name, having a dedicated attribute for `testnet` would be of great use for filtering.

I don't have a problem doing the legwork of adding them, but wanted to get feedback on whether such a PR would be accepted.

**Comment by ligi** [comment]
I am not really sure about this tbh. What defines a "testnet"? I think you can also kinda deduct it from having a faucet. I would say: If there is at least one faucet then it is a testnet. Is there a reason/case this approach would not work for you?

**Comment by DefiDebauchery** [comment]
Pedantically, you used to be able to get faucets on Eth Mainnet, as well as Fantom, so I'm not totally sure that's a good metric.

I feel like testnets are pretty fairly defined, though - they represent a non-production playground. Chainlist does seem to categorize these, which is potentially on name alone (I haven't looked), but not sure that's as much of a foolproof way of determining than a specific attribute would be.
