### ISSUE TITLE
CC'ing all editors: @lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1

### ISSUE THREAD

**Issue by amandaweston1306** [ethereum-lists/chains#1473]
CC'ing all editors: @lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1

__Originally posted by @Pandapip1 in https://github.com/ethereum/EIPs/pull/5502__

**Comment by ligi** [comment]
?

**Comment by Pandapip1** [comment]
~~Probably~~ Definitely a spam bot.
