### ISSUE TITLE
PHI Network Logo Not Showing On Chainlist 

### ISSUE THREAD

**Issue by Phinetwork** [ethereum-lists/chains#1505]
Added Logo But Does not show how is logo image uploaded without .png but still shows have tired a few times & doesnt seem to be working.

**Comment by ligi** [comment]
please open the issue there

**Comment by Phinetwork** [comment]
> please open the issue there

Open the issue where? Do u have documentation on how to make the logo show have added logo but doesn't show

**Comment by ligi** [comment]
here: https://github.com/DefiLlama/chainlist
