### ISSUE TITLE
Adding PreCommit Hook and Gitpod Support

### ISSUE THREAD

**Issue by ashutoshpw** [ethereum-lists/chains#1521]
I am planning to add a pre-commit hook to the repository so that it can do some basic checks before someone push to the repository. If these checks fails, they will get to see the error in the terminal itself. 

Although we have GitHub Workflows setup for few of these but that is not enabled for the 1st time contributors, so pre-commit hooks could be a good idea to reduce the PR review time.

Some checks as
- Check JSON schema and formatting with prettier
- Checking validity of IPFS Schema and check if those are reachable. 
- Check valid URLs for testnet and faucets
- Check Icon hash with IPFS hash 

### Why Gitpod?
As a developer the local machine of ours might have nodejs or might not have nodeJS and other relevant setup such as the prettier extension for the repository. Setup for Gitpod will open a Cloud Instance of VS Code on gitpod.io (for free) with the relevant setup so it will eradicate the setup time for any new developer and anyone can quickly make any additions/removals to the lists.

Overall, it will save time for contributors as well as reviewers. 

---

I can work on it if it seems to be reasonable.

**Comment by ashutoshpw** [comment]
@ligi thoughts on this?

**Comment by ligi** [comment]
Thanks for the thought - not yet sure about it though - need to give it more thought but not really the time currently.

**Comment by ligi** [comment]
the ipfs part is also really problematic - maybe you just try it - if you just start an IPFS daemon and directly request a hash this will most of the time not work.

**Comment by ashutoshpw** [comment]
What about directly accessing the hash from a public gateway such as cloudflare-ipfs.com ?

Example
https://cloudflare-ipfs.com/ipfs/QmdwQDr6vmBtXmK2TmknkEuZNoaDqTasFdZdu3DRw8b2wt

I checked a few IPFS icons listed in repo, most of them is not opening up at all.

**Comment by ligi** [comment]
yea - this is the problem - that's why I started the iconDownloads thing
sometimes even if it is pinned on pinata you cannot see it on other gateways. So far the whole thing seems to be still horribly broken ..

**Comment by ligi** [comment]
and so far I just merged if I could access the icon once to check the icon size ..

**Comment by ashutoshpw** [comment]
Any thoughts on using [Skynet](https://skynetfree.net/ ) for icon hosting (powered by [Sia](https://sia.tech/)) or [Arweave](https://www.arweave.org/), it seems files are more reliable on these platforms

I will look into if something could be done about this IPFS problem.
