### ISSUE TITLE
invalid JSON format in chains.json

### ISSUE THREAD

**Issue by gasolin** [ethereum-lists/chains#156]
current https://chainid.network/chains.json has an empty token as the first entry.
It contains invalid JSON format `"chainId": , "networkId": ,`

```
  "name": "",
    "chainId": ,
    "shortName": "",
    "chain": "",
    "network": "",
    "networkId": ,
    "nativeCurrency": {"name":"","symbol":"","decimals":},
    "rpc": [],
    "faucets": [],
    "infoURL": ""
  },
```

**Comment by ligi** [comment]
oh - thanks for the info - guess this came with the deprecated folder
