### ISSUE TITLE
When doing PR come across this error 

### ISSUE THREAD

**Issue by amory1997** [ethereum-lists/chains#1598]
Here is my PR ,[https://github.com/ethereum-lists/chains/pull/1595](https://github.com/ethereum-lists/chains/pull/1595) 

fatal: unable to access 'https://github.com/ethereum-lists/chains/': The requested URL returned error: 403

Error: Process completed with exit code 128.

Can someone help me with the issues, and tell me what's wrong with my PR, thank you in advance

**Comment by steveliupai** [comment]
Same issue for me

**Comment by FrederikBolding** [comment]
Rebasing your PR should fix the Prettier issue now! 😄
