### ISSUE TITLE
I got a error while doing the PR which are all legal

### ISSUE THREAD

**Issue by amory1997** [ethereum-lists/chains#1609]
Here is the tetail of the [error：](https://github.com/ethereum-lists/chains/actions/runs/3075634680/jobs/4969200549)

```
No files added to commit
remote: Permission to ethereum-lists/chains.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/ethereum-lists/chains/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

Here is my PR:
[https://github.com/ethereum-lists/chains/pull/1608](https://github.com/ethereum-lists/chains/pull/1608)

I have tried the PR many times (more than five times I think),
I also deleted the fork repository of chains and forked again then made the pull request but the error remained the same;
And all the code was checked via [Prettier](https://prettier.io/).

Can anyone help me to solve the [error](https://github.com/ethereum-lists/chains/actions/runs/3075634680/jobs/4969200549) above ?
Thank you in advance to who care about the issue.

**Comment by FrederikBolding** [comment]
This should be fixed now - you may need to rebase any existing PRs!

**Comment by amory1997** [comment]
> This should be fixed now - you may need to rebase any existing PRs!

Thank you for the suggestion. my PR has been verified properly.
