### ISSUE TITLE
ETH PoW Mainnet

### ISSUE THREAD

**Issue by akincibor** [ethereum-lists/chains#1673]
Network name — ETHW-mainnet
New RPC URL — https://mainnet.ethereumpow.org
Chain ID — 10001
Currency symbol — ETHW
Block Explorer URL — https://mainnet.ethwscan.com

**Comment by ligi** [comment]
That chainID is used already - I [warned them in the PR's](https://github.com/ethereumpow/go-ethereum/pulls) multiple times - they did not listen - this will not be merged ..
