### ISSUE TITLE
JSON Schema Does Not Support Chain -> Multiple Networks

### ISSUE THREAD

**Issue by rickmark** [ethereum-lists/chains#1829]
If I have (after some working through things) figured correctly:

rpcs ought be a dictionary with a shape like (i presume the matching network id can use rpcs for backward compat):

```json
{
  "chainId": 1337,
  "name": "Geth Testnet",
  "title": "Geth Ethereum Testnet",
  "chain": "ETH",
  "networks": {
      1337: {
         "rpc": ["http://127.0.0.1:8545"],
         "faucets": []
      },
      5777: {
         "rpc": ["http://127.0.0.1:7545"],
         "faucets": []
      }
  },
  "nativeCurrency": {
    "name": "Ganache Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "shortName": "geth"
}

```

**Comment by ligi** [comment]
thanks for the suggestion - unfortunately this is not backward compatible and so needs more thought. 
But I wanted to revamp the RPC section anyway - so maybe it can be done in combination. I wanted to add CAIPs (to be created) in an array alongside the RPCs that define what methods the RPC support (to differentiate archive and other RPCs as well as allow different chains like L2s to have other methods.
In the meantime let me understand use-cases of having different RPCs on different networks of one chain. Can you elaborate on use-cases here?
