### ISSUE TITLE
Switch to chainlist.org front end

### ISSUE THREAD

**Issue by bmann** [ethereum-lists/chains#188]
https://twitter.com/mr_ligi/status/1371807404715819010

@ligi @pedrouid

**Comment by pedrouid** [comment]
Agreed! Love what @andreconje did with the registry 👌

**Comment by ligi** [comment]
true! The only question I have what we do domain-wise. Just rug-pulling chainid.network feels a bit wrong as it has been out for a while and there might be upstream dependencies. Also I  think ".network" fits better here than ".org" - also the org donain is quite new and there might not be many dependencies on it.
But I think we should use the frontend @andrecronje did for sure - it is just so much better than what we had.
Perhaps the org can just be switched off (maybe with some grace period where it redirects to the .network) - don't see much point in having/paying for 2 domains with the same content.

**Comment by bmann** [comment]
I think `.org` more clearly indicates "this is an open source community thing".

Domains are easy to re-direct in any case. 

But it really doesn't matter which domain. The data and the flat JSON file as API is the useful part. 

Forking the code and replacing master here is the easy thing to do. 

The source is a Next.js. So, needs a GH Actions build step and deploy to Fission or Fleek -- or there is probably a way to write a build to a branch to keep it simply on GitHub Pages.

**Comment by pedrouid** [comment]
we can still have both chainId.network and chainlist.org pointing to the same website while maintaining the frontend on the same repo as the registry

also we could still maintain the backwards capability by having an aggregated json file as it's currently exposed on the chainid.network url

**Comment by pedrouid** [comment]
alternatively we could just have the chainid.network being maintained purely as legacy url where it simply exposes a json file and the default route redirects to the new website

**Comment by pedrouid** [comment]
chainlist uses next.js which can be easily setup with either Vercel or Netlify

however this registry does have a pre-build requirement for the aggregated json

we just need to separate the two builds (json and frontend) from each other

then set them up sequentally so that aggregated json is ready when the frontend build starts

**Comment by ligi** [comment]
I migrated away from jekyll now (in preparation to serve data on lists.eth via ens) and redirect the site to chainlist.org now
Also chainlist.org now dynamically loads the json
could be better even - but I think this is a step in the right direction
