### ISSUE TITLE
Gitcoin Grant

### ISSUE THREAD

**Issue by bmann** [ethereum-lists/chains#19]
@pedrouid @ligi I've already talked a bit to Pedro about this in a related email thread.

I'd like to create a Gitcoin Grant for this chains work, set at 250DAI per month.

This would go into a multisig, 2-of-3 wallet. I set it up already, let me know what addresses you want me to use for you two.

The purpose of this is to lead by example in showing the community that they can support work they find valuable, and to support the Gitcoin Grants initiative -- and more importantly the CLR matching that they are experimenting with https://medium.com/gitcoin/gitcoin-grants-clr-matching-ecbc87b10038

Not about the money, but rather an acknowledgement of value, and a default way to ask for support / thanks, which we would post on the public site and in the README.

**Comment by ligi** [comment]
Interesting experiment - found it here: https://gitcoin.co/grants/44/chainid-network
Not sure if someone would put money towards this - but this can be part of the experiment. Would be great if you could be compensated for the expenses with the domain. Other than that I am not sure what we would use the money for. I do not see enhancements that could be really bounty worthy.

**Comment by bmann** [comment]
Yeah, I went ahead and experimented with setting it up :) Turns out it's super simple. 

My point is that this is all work. If someone wants to support it, wants to say "thanks" or just have a way to give back -- here it is.

Domain is minor -- the time that the three of us spend on it is the most "expensive".

Anyone objections to putting it on the about page as a way to support this?

**Comment by ligi** [comment]
closing this as it is done
