### ISSUE TITLE
New field tx_type

### ISSUE THREAD

**Issue by coccoinomane** [ethereum-lists/chains#1901]
Hi there!

Did you ever consider to add a tx_type field to differentiate between chains implementing EIP-1559 (tx_type=2) and those who don't (tx_type=1)?

It would be very useful for clients who need to send transactions on the chains, for example my project [web3cli](https://www.github.com/coccoinomane/web3cli/).

I am willing to make a PR if there's consensus on it 🙂

Cheers,
Cocco

**Comment by coccoinomane** [comment]
Why not something like this?

```json

  "features": [
    {
      "name": "EIP1559",
      "since_block": 123,
      ...
    },
    ...
  ]

```

If needed, we can always add extra properties to 'feature' at a later time, without compromising backward compatibility.

**Comment by ligi** [comment]
yea - sometimes it might not be a block - but maybe this is enough for the MVP

**Comment by coccoinomane** [comment]
Thanks @ligi for the quick commit!

I have made a pull request adding the `EIP1559` feature to Avalanche 🙂
