### ISSUE TITLE
Görli or Goerli naming leads to confusion

### ISSUE THREAD

**Issue by vbaranov** [ethereum-lists/chains#1912]
It would be awesome to standardize Görli instances naming. Some of the instances based on Görli have `Görli` in the name and others - `Goerli`. It leads at least to confusion, for example, in searching at chainlist.org.

If to find by `Görli`:

<img width="802" alt="Screenshot 2022-11-21 at 16 37 34" src="https://user-images.githubusercontent.com/4341812/203069134-135bb057-0ade-42da-8b4d-fd4f9fb21ff3.png">

If to find by `Goerli`:

<img width="774" alt="Screenshot 2022-11-21 at 16 38 07" src="https://user-images.githubusercontent.com/4341812/203069222-2866e32f-f9eb-44d7-aeb4-5385f6d76789.png">

**Comment by ligi** [comment]
I think I would settle around goerli to be more international 
Wondering what to do on the CI side though to slip new inconsistencies slip in. Maybe not allow non ASCII chars in the first place.
