### ISSUE TITLE
i can not find our chain in  webstie home

### ISSUE THREAD

**Issue by Zombieliu** [ethereum-lists/chains#200]
https://chainlist.org/ i can not search sgc testnet id 102  . Is it a delay problem?

**Comment by ligi** [comment]
yea - I think chainlist.org needs to create a new release so the new chains are listed - but @antonnell can tell you more about this
you can see it already on https://chainid.network - but this one does not yet have the "add to wallet" function

**Comment by Zombieliu** [comment]
> yea - I think chainlist.org needs to create a new release so the new chains are listed - but @antonnell can tell you more about this
> you can see it already on https://chainid.network - but this one does not yet have the "add to wallet" function

yep, it break my heart 
https://networklist-org.vercel.app/ i can see at here but https://chainlist.org/ public website is not . so sad

**Comment by ligi** [comment]
ouch - you are easily heard-broken - don't be sad about things like this! Also guess it won't take too long until it appears there.
Here a tea in the meanwhile :tea:

**Comment by ligi** [comment]
seems it is now listed in 1.0.3
