### ISSUE TITLE
Add icon URLs

### ISSUE THREAD

**Issue by edmundedgar** [ethereum-lists/chains#202]
Now that we have EIP-3085 it becomes useful for dapps to have a maintained list of parameters they can use to create "add network" requests. The chains.json here file works great for this purpose, except that it's missing a couple of fields: 

- The block explorer, mentioned in https://github.com/ethereum-lists/chains/issues/59
- The icon, which we see used here for example: https://forum.1hive.org/t/its-finally-here-the-custom-network-api/2659

We don't necessarily need them for all networks, just the main ones would be fine.

**Comment by ligi** [comment]
Yea - actually Icons is easier than the block explorer so I will start with this one.
I suggest to make it an array to cater for different sizes / formats and enforce the URL to be a web3 URL (ipfs:// to start with) so we can pin it in the process.
Does this work for everyone:

```json
{
    ...
	"logo": [{
			"url": "ipfs://myIPFSurl",
			"width": 128,
			"height": 128,
			"format": "png"
		},
		{
			"url": "ipfs://myIPFSurlForSVG",
			"format": "svg"
		}
	]
}
```

If we can get rough consensus around this I would add support for it to the CI and hope for some help with backfilling important chains.

**Comment by edmundedgar** [comment]
That looks good to me - I'm not sure whether metamask will handle raw ipfs urls correctly or not but if not I guess it's not a big deal for the code that consumes that to switch it for a gateway.

**Comment by ligi** [comment]
yea - we could also offer a transformed json that changes the URLs to use a prefix

**Comment by ligi** [comment]
Just had one thought when starting to add support: maybe it makes sense to have the icon definitions in different files and just have references to it in the chain definitions. 
Background: some chains will share the icon definitions (e.g. between main and testnets) so this would make things WET and IMHO we should keep things DRY.

**Comment by edmundedgar** [comment]
Sounds good to me, I guess that'll mean we'll definitely want to be able to generate a transformed json but that's probably a good idea anyhow
