### ISSUE TITLE
Add chainID for KorthoTest

### ISSUE THREAD

**Issue by Eric0718** [ethereum-lists/chains#208]
{
  "name": "KorthoTest",
  "chain": "Kortho",
  "network": "Test",
  "rpc": [
    "https://www.krotho-test.net"
  ],
  "faucets": [
  ],
  "nativeCurrency": {
    "name": "Kortho Test",
    "symbol": "Kto",
    "decimals": 11
  },
  "infoURL": "https://www.kortho.io/",
  "shortName": "Kortho",
  "chainId": 8285,
  "networkId": 8285
}

**Comment by Eric0718** [comment]
Can someone help me with my request? I just want to add a chianId to KorthoTest, this is my first time to do something like this, please correct me if I do something wrong, thanks.

**Comment by ligi** [comment]
please submit it as a PullRequest - then I will merge

**Comment by Eric0718** [comment]
> 请以PullRequest的形式提交-然后我将合并

Ok,I will do it,thank you.
