### ISSUE TITLE
Add faucets

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#21]
I think this could be very practical. Also a defined token for an address.In KEthereum I use a token like this for it:

` "https://goerli-faucet.slock.it/?address=%address%"`

**Comment by bmann** [comment]
Oh this would be great! 

Don’t know about the token — feels like faucet as a URI field array makes sense, not sure if embedding the token into the JSON makes sense.

**Comment by ligi** [comment]
great! to clarify the token - this address will be prefilled in the address field in the faucet if available. This makes UX much better as users do not need to enter it then. I would signal to include it.

**Comment by bmann** [comment]
Can I see a couple of examples to better understand?

**Comment by ligi** [comment]
e.g. 

"https://goerli-faucet.slock.it/?address=%address%"

would be a faucet url - and the wallet for example would replace %address% with the users current address

**Comment by ligi** [comment]
faucets should be an array of object with the properties: url,address, with_tokens, max_amount

not 100% about tokens and amount - perhaps as list of address+amount?

**Comment by pedrouid** [comment]
LGTM 👍 Let's just go ahead and add this one to the spec
