### ISSUE TITLE
_data.logos IPFS hashes cid version 1(bafy...) vs version 0 (Qm...)

### ISSUE THREAD

**Issue by kevin-wad** [ethereum-lists/chains#2159]
Hi,
I was wondering if you only accept Qm... ipfs hashes or you would also accept the latest ipfs version that starts with bafy...
New online ipfs uploaders only return bafy... type hashes but I will find a way to get an Qm... hash if necessary, by the way if you have a website in mind where we can currently get old hashes please let me know.
Thanks

**Comment by ligi** [comment]
both versions are accepted

**Comment by kevin-wad** [comment]
Ok thanks!
