### ISSUE TITLE
Logo not showing for recently added network

### ISSUE THREAD

**Issue by xo-dex** [ethereum-lists/chains#2215]
Hi guys

Just wondering if there's a problem due to the logo not showing for our recently added network to chain list?

https://chainlist.org/chain/2415

PR:
https://github.com/ethereum-lists/chains/pull/2175

Is there a way i can fix this?

Thanks

**Comment by ligi** [comment]
please open this issue on chainlist.org - it works fine with https://chainid.network and https://chainlist.wtf - and thats the sites we are running
