### ISSUE TITLE
Logo Missing from Chain 6066 and 6065

### ISSUE THREAD

**Issue by bladepool** [ethereum-lists/chains#2299]
I Reviewed IPFS for Chain and I can get the logo with no problem, however, I don't see it being displayed correctly on the site. How can I fix the same? Any advice will be great.

Thanks,
Bladepool
Tres Chain

**Comment by ligi** [comment]
from the data side of things all seem to be good - please open the issue with the frontend you are interested in - if it is really a data problem feel free to reopen

**Comment by ligi** [comment]
opened an issue here: https://github.com/FrederikBolding/chainlist/issues/34
