### ISSUE TITLE
Add mainnet boolean

### ISSUE THREAD

**Issue by kopeboy** [ethereum-lists/chains#2351]
Can't find a way to distinguish mainnets from testnets, which is VERY usefull.

**Comment by ligi** [comment]
what's the use-case?
Usually a good indicator is if there is a faucet

**Comment by Shahidul783** [comment]
> Can't find a way to distinguish mainnets from testnets, which is VERY usefull.

**Comment by kopeboy** [comment]
The usecase is not showing testnets in any user facing app that fetches networks from this list.
I can filter on "test" or "dev" in the name field but it's not well defined and prone to errors.
Faucet field is not good either, you can have mainnets with faucets and testnets without it.
I think adding a specific field that distinguishes the items in the list is usefull for the purpose of this repo.

**Comment by kopeboy** [comment]
Where can we see what's planned and is planning a collaborative effort? 🤔

**Comment by ligi** [comment]
this is what is planned: https://github.com/ethereum-lists/chains/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement

planning is a semi-collaborate effort - things can be suggested - but only core contributors decide

I think this is not worth doing - even though it would be easy.
What is even a testnet - how do you define it?
Why would you want to filter testnets?

**Comment by ligi** [comment]
I still do not think this is a good idea to have a isTestNet or isMainNet option.
What I could imagine to add:
```json
{ "priceTracker": { "name": "", "standards: [], "address" } }
```

If something is a testnet is just simply not a boolean value. 
 - What is with Goerli? It's token has value now ..
 - What is with Mainnnet? People test on it ..
