### ISSUE TITLE
Logos for Autonity testnets (65010000 and 65100000) not showing

### ISSUE THREAD

**Issue by flofrie** [ethereum-lists/chains#2359]
PR #2323 added icons for Autonity testnets Bakerloo and Piccadilly (65010000 and 65100000), and passed all the checks, a few days ago, but the logos are still not showing up on [chainid.network](https://chainid.network/), which is the site that according to this repo's "About" section, it publishes out to.

This seems different from https://github.com/FrederikBolding/chainlist/issues/34, since for that case, it has since been resolved _without_ them actually changing or updating the data. So it seems their data remained the same as committed some months ago, but eventually their logo showed up on the site. So it looks like something got fixed in the site deployment. -- However, Autonity's still don't show, so whatever resolved the situation for 6065, didn't seem to fix it for Autonity.

What are the next steps we can take to investigate?

**Comment by flofrie** [comment]
In the meantime, trying to see whether doing them as PNG will work. https://github.com/ethereum-lists/chains/pull/2360

**Comment by ligi** [comment]
please open this issue here: https://github.com/FrederikBolding/chainlist
yea - seem to have something to do with SVG - but it is a frontend issue and should be opened there
