### ISSUE TITLE
Add gas price provider

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#24]
the simplest one for e.g. xDAI could be "fixed" to 1Gwei - for others we should define interfaces (e.g. to ethgasstation)

**Comment by pedrouid** [comment]
This would only work if all gas price providers followed the same interface, the reason this list even works is because we only list EVM blockchains which have high mutual coverage of the same JSON RPC api spec

**Comment by ligi** [comment]
and with EIP-1559 this might get obsolete anyway. Perhaps we should keep it real simple and just do the ones that have a fixed gas price like xDAI?
