### ISSUE TITLE
Add RIKEZA Blockchain mainnet and testnet

### ISSUE THREAD

**Issue by iamakshaykumar** [ethereum-lists/chains#2426]
Add RIKEZA Blockchain mainnet and testnet

https://github.com/iamakshaykumar/chains/commit/fc63b86958fcee30d6b29b0ebd5da4b5ea4abe8b

testnet 
{
    "name": "Rikeza Network Testnet",
    "chain": "RIK",
    "rpc": ["https://testnet-rpc.rikscan.com/"],
    "faucets": [],
    "features": [{ "name": "EIP155" }, { "name": "EIP1559" }],
    "nativeCurrency": {
      "name": "Rikeza Testnet",
      "symbol": "RIK",
      "decimals": 18
    },
    "infoURL": "https://rikeza.io",
    "shortName": "rik",
    "chainId": 12715,
    "networkId": 12715,
    "explorers": [
      {
        "name": "RIK Scan Explorer",
        "url": "https://testnet.rikscan.com/",
        "standard": "EIP3091"
      }
    ]
  }

mainnet

{
    "name": "Rikeza Network Mainnet",
    "chain": "RIK",
    "rpc": ["https://rpc.rikscan.com"],
    "faucets": [],
    "features": [{ "name": "EIP155" }, { "name": "EIP1559" }],
    "nativeCurrency": {
      "name": "Rikeza",
      "symbol": "RIK",
      "decimals": 18
    },
    "infoURL": "https://rikeza.io",
    "shortName": "rik",
    "chainId": 1433,
    "networkId": 1433,
    "explorers": [
      {
        "name": "RIK Scan Explorer",
        "url": "https://rikscan.com",
        "standard": "EIP3091"
      }
    ]
  }

**Comment by ligi** [comment]
open a PR not an issue
