### ISSUE TITLE
[New Chain / Network] Issue with "QuickSwap"

### ISSUE THREAD

**Issue by ttodua** [ethereum-lists/chains#251]
Hi.
I am not requesting to add new one, just asking:

This site: https://quickswap.exchange/#/swap  adds network named "Matic Network", however, metamask says it doesn't match records (based on your data) and gives warning.
Can you tell/verify if that site adds malicious network or that is legit network, but not added by you yet?

**Comment by ligi** [comment]
can you please find out what records are different?
