### ISSUE TITLE
Network ICONS are not displayed

### ISSUE THREAD

**Issue by bCoder778** [ethereum-lists/chains#2571]
The network of 8131 has uploaded PNG and related documents a long time ago, but the network icon has not been displayed. Could you please help to see what the problem is? Thank you very much

**Comment by ligi** [comment]
They are displayed:
![image](https://user-images.githubusercontent.com/111600/229397955-8b102a18-9e64-4737-9426-9fdc93236bd8.png)

**Comment by bCoder778** [comment]
Thanks, yes, but I see it's not on chainlist.org

**Comment by ligi** [comment]
chainlist.org is a 3rd party things with problems since it was taken over by a lame entity - don't use it

**Comment by bCoder778** [comment]
ok, thank you very much
