### ISSUE TITLE
Adding TTcoin Smart Chain Explorer

### ISSUE THREAD

**Issue by Tayfuntaner** [ethereum-lists/chains#2623]
How will we add the network with the information below to your systems?

**Blokchain Name:** TSC Mainnet
**Symbol:** TC
**Coin Name:** TTcoin
**Chain-ID:** 330844
**RPC:** https://mainnet-rpc.tscscan.com/
**Explorer:** https://tscscan.com/

**Comment by ligi** [comment]
submit a PR
