### ISSUE TITLE
Unable to see chain icon

### ISSUE THREAD

**Issue by randy75828** [ethereum-lists/chains#2681]
Hi, i recently made a PR to add my chain (carbon) into chainlist. The PR is approved and merged already [(https://github.com/ethereum-lists/chains/pull/2668)](url). However, im still unable to see the icon for my chain appearing on the UI. Is there something im missing? Would appreciate any help on this!

<img width="886" alt="image" src="https://user-images.githubusercontent.com/44086461/233277335-7e82bc95-50be-4e78-af22-3775eaaa2768.png">

**Comment by ligi** [comment]
Please open this bug on the frontends
