### ISSUE TITLE
Reclaim the network id 7777

### ISSUE THREAD

**Issue by GDCC-COIN** [ethereum-lists/chains#2745]
GDCCoin is listed on various exchanges, such as LBank, BKEX, and BitMart. You can find the links to these exchanges below. You can also check the price and market cap of GDCCoin on CoinGecko and CoinMarketCap.

GDCCoin, a new-age protocol that caters to web3.0 services and community-driven technology, is launching on April 20, 2022
https://web.archive.org/web/20220420062844/https://www.gdccoin.io/
coingeko link https://www.coingecko.com/en/coins/global-digital-cluster-co
coimarket link https://coinmarketcap.com/currencies/global-digital-cluster-coin/

We also want to inform you that we need to reclaim the network id 7777 which was launched way before the Rise of the Warbots Testnet. This is a necessary step to ensure the security and stability of our network. We appreciate your cooperation and support in this matter.

**Comment by ligi** [comment]
only PRs will be considered
