### ISSUE TITLE
Add project: eth-chains

### ISSUE THREAD

**Issue by taylorjdawson** [ethereum-lists/chains#276]
I created a module [eth-chains](https://github.com/taylorjdawson/eth-chains) to use the chains within node projects as I thought that it could be helpful. If you also think it is helpful could I add it to the Usages section? Feedback welcome!

**Comment by ligi** [comment]
Nice! If you make a PR to the README adding it to the usage section I will merge it.

**Comment by taylorjdawson** [comment]
Done!

**Comment by ligi** [comment]
closed by #288 - thanks!
