### ISSUE TITLE
Camino chain logo not shown

### ISSUE THREAD

**Issue by Noctunus** [ethereum-lists/chains#2785]
Hello there!

We (Camino) have added the chain logo quite some time ago but it's not shown in for instance https://chainlist.org/chain/500 and https://chainlist.org/chain/501

The logo definition is there: https://github.com/ethereum-lists/chains/blob/master/_data/icons/camino.json
And the IPFS link is valid as the download succeeded: https://github.com/ethereum-lists/chains/blob/master/_data/iconsDownload/QmSEoUonisawfCvT3osysuZzbqUEHugtgNraePKWL8PKYa

This is also added to the deployment: https://github.com/ethereum-lists/chains/actions/runs/4928418015/jobs/8806767135#step:3:5122

Is there also the need to add something else so that it get's deployed correctly?

Thanks for the help!
Alex

**Comment by ligi** [comment]
it is shown:
![image](https://github.com/ethereum-lists/chains/assets/111600/03254e82-4e6f-4fdf-8d45-8ee58d628ec6)
just not on chainlist org - file an issue there - or better do not use them.
