### ISSUE TITLE
Add chainIDs from IN3 whitepaper

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#29]
in section 6.1 of the incubed whitepaper:

https://download.slock.it/whitepaper_incubed_draft.pdf

we find some more chainIDs that are not in our list. I am not yet sure where some of them originate (e.g. IPFS as I am not aware of any EIP155 signing there - also googleing for 0x07da ipfs mainly surfaces the slock.it in3 whitepaper)
We should still think about adding them - also e.g. the chainSpec field from their config: https://github.com/slockit/in3/blob/master/src/client/defaultConfig.json
I would even signal to add all chain-specific data from this json file so we can run IN3 clients for the chains with this information. But this might be a bit opinionated and out of scope - cc @pedrouid @bmann 

@simon-jentzsch @CJentzsch can you elaborate where 0x07da from the whitepaper is coming from?

**Comment by Systemfehler1979** [comment]
Nein
