### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by Bobbylee79R** [ethereum-lists/chains#3040]
ethereum:0x8FeF8cFbDcB4c2491F71Cf0BBDD8183bD4002E9c@1![myaddr.png](https://github.com/ethereum-lists/chains/assets/124235115/346feee0-fe20-41b9-a8cd-bfedfbfdbd44)

Bobbyleeribinette79@gmail

**Comment by IvanGoncha** [comment]
Ем

ср, 21 июн. 2023 г., 12:57 Bobbylee79R ***@***.***>:
