### ISSUE TITLE
use svgo

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#3136]
There are some problems with SVG images - maybe we could leverage [svgo](https://github.com/svg/svgo) to make them a) smaller b) maybe remove problematic tags

**Comment by ipule0966** [comment]
Good

**Comment by Karlitos88** [comment]
Discussions not problem and my imposibility not 
Image sucess day content my personal account. TheNewFactory@Art&Contents 
JUANCARLOSSNET.ETH

**Comment by Karlitos88** [comment]
Alucinant versión inclement explications my  life Sucess lmportant verify advans option continúe verbal reactions not logic leccions and humor TheNewFactory@Art&Contents 
JUANCARLOSS1977

**Comment by Drunsquirrelrum** [comment]
Eth Fitbit

**Comment by dinhtuananhne** [comment]
>

**Comment by dinhtuananhne** [comment]
``

**Comment by dinhtuananhne** [comment]
[](url)

**Comment by Andarina** [comment]
#4478 
<git_commit>

**Comment by Toddgan** [comment]
Good done

**Comment by ghini10** [comment]
..
