### ISSUE TITLE
Payment https://metamask.app.link/send/0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD@1/transfer?address=0x49F964310dc38D935AB1b2f826ba5881c2D70f7D&uint256=1.571055180988070494208e21

### ISSUE THREAD

**Issue by Bobbylee79R** [ethereum-lists/chains#3270]
https://metamask.app.link/send/0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD@1/transfer?address=0x49F964310dc38D935AB1b2f826ba5881c2D70f7D&uint256=1.571055180988070494208e21

**Comment by Mikemfnb1** [comment]
sweet
