### ISSUE TITLE
SVG not showing up on the main site

### ISSUE THREAD

**Issue by santiagotrujilloz** [ethereum-lists/chains#3332]
Hey guys, I am wondering why after passing all 4 tests, the icon is not showing up? the IPFS URL is working properly.
Something else we can do from our side? thank u!

Here is the [icons/swisstronik.json](https://github.com/ethereum-lists/chains/blob/master/_data/icons/swisstronik.json)

![image](https://github.com/ethereum-lists/chains/assets/83420872/d30c804c-400e-4df8-b644-fab9ccfd73b1)

![image](https://github.com/ethereum-lists/chains/assets/83420872/1817f981-5807-4b6a-b5f4-49e4bfc8898b)

**Comment by ligi** [comment]
please open the issue in the frontend(s)

**Comment by santiagotrujilloz** [comment]
@ligi What's the front-end repo?
