### ISSUE TITLE
Rules of adding a new chain id

### ISSUE THREAD

**Issue by calvinaco** [ethereum-lists/chains#338]
Hello, I would to learn more about the rules of claiming a chain id here.
- Is it a must to have the chain running when adding a chain id?
- If the first question is yes. Since a chain may want to secure the mainnet chain id before it is launched. Is it ok if one already have a testnet chain id and add in advance the mainnet chain id?
- From other PR discussion the chain ID adding is first come first claim basis, if there's a dispute the genesis file will be used to resolve.
    - Is there any way a chain can secure a chain id? Can it be considered secure if at the time of PR the chain id is not claimed by other chain or PR in this repo?
- There are some lower numbers who have not been claimed yet, the smallest one I saw is 19. Are those numbers usable? Is there anything a chain should be aware of when using those numbers?

Thank you.

**Comment by ligi** [comment]
* yes the chain should be running
* chains are looked at independently - so yes you can submit a testnet before
* we did not yet think about "securing a chainId" - not really sure I like the idea as I see room for abuse here - can you elaborate on your reasons or asking?
* yes - all numbers that are not yet submitted should be usable - but I think it is safer to use a number that is less likely to be a shelling point as not the time of the PR is important - but the genesis

**Comment by calvinaco** [comment]
@ligi thanks for the explanation

> we did not yet think about "securing a chainId" - not really sure I like the idea as I see room for abuse here - can you elaborate on your reasons or asking?

Sure I understand your concern, the reason I raise this is base on a genuine and reasonable use.

If it's a testnet usually it is more flexible and say there's a collision of chain id one can change it on the new network or so. But when it comes to a mainnet, once the chain id is decided and the network starts it is hard to change. So when we launch our mainnet, we want to make sure the chain id does not collide with other chains and avoid any potential contest of the chain id for the community best interest.

So the "securing a chainid" is based on this idea. I think it make sense to a testnet to be running before one add a chain id to avoid abuse. But does it make sense if a testnet is already running, that chain can add one more chain Id for mainnet? I hope this make sense and if it is not how the community think about it we are open and would love to learn more about how it usually work.

Thank you.

**Comment by calvinaco** [comment]
@ligi thanks for the explanation

> we did not yet think about "securing a chainId" - not really sure I like the idea as I see room for abuse here - can you elaborate on your reasons or asking?

Sure I understand your concern, the reason I raise this is base on a genuine and reasonable use.

If it's a testnet usually it is more flexible and say there's a collision of chain id one can change it on the new network or so. But when it comes to a mainnet, once the chain id is decided and the network starts it is hard to change. So when we launch our mainnet, we want to make sure the chain id does not collide with other chains and avoid any potential contest of the chain id for the community best interest.

So "securing a chainid" is based on this idea. I think it make sense to a testnet to be running before one add a chain id to avoid abuse. But does it make sense if a testnet is already running, can the chain add one more chain Id for mainnet? I hope this make sense and if it is not how the community think about it we are open and would love to learn more about how it usually work.

Also perhaps "securing" is a bit controversial here, since the determination factor is the genesis time, so maybe it will better to make a way to let the community know a chain is going to use certain chain id for mainnet and avoid collision. Again we do not want to introduce abuse but the intention is we want to make sure we don't pick a mainnet chain id that later found is colliding with another chain only.

Thank you.

**Comment by ligi** [comment]
I understand now - if you have a good idea how to solve this I am all ears ;-)

**Comment by ligi** [comment]
I made a note in the README about it: 5bd54d518c8b59c47de15c1bf954139fae9a2605

closing this issue as I see no action to be taken here
