### ISSUE TITLE
Validate formatting keeps failing

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum-lists/chains#3483]
Is there any reason why this keeps failing. the image is retrievale and JPEG format on IPFS and from what i can see my JSON is the correct structure like most other chains 

https://github.com/ethereum-lists/chains/actions/runs/6130081727/job/16640525482

**Comment by ligi** [comment]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`
