### ISSUE TITLE
add bridge information to parent field

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#349]
currently the parent field looks like tis:

```json
{
...
"parent": {
 "type" : "L2",
 "parent": "eip155-1"
}
}
```

I suggest we add a "bridge" field. Just wondering if we need more than just an URL.

**Comment by khai911013** [comment]
#https://github.com/vuejs/vue-cli/pull/4090#issue-284357693

**Comment by ligi** [comment]
@khai911013 ?

**Comment by khai911013** [comment]
> #374

**Comment by ligi** [comment]
I think we make it future proof by making it an array of objects like this:

```json
{
...
"bridges": [ {"URL":"https://bridge.arbitrum.io"} ]
}
```
