### ISSUE TITLE
This is failing on Gradle, but running gradle before PR there is no issues

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum-lists/chains#3505]
I just want to update my RPC endpoints to SSL but getting errors with the gradle process, any idea why ?

https://github.com/ethereum-lists/chains/actions/runs/6177160777/job/16767688420?pr=3504

**Comment by ligi** [comment]
it clearly states it in the details of the failing task:
`RPC chainId (1986) does not match chainId from json (1985)`
