### ISSUE TITLE
Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by Farid116** [ethereum-lists/chains#3531]
https://github.com/ethereum-lists/chains/pull/3525

Please tell me how to fix the error

"url": "ipfs://QmYvFVprVdAGJH4iHUCXGEmy7pq8MMfxEjM64SuXutz9qx",
"width": 256,
"height": 256,
"format": "png"
}
+]
Error: Process completed with exit code 1.

npx prettier --write _data//.json

Checked, there are no errors.
Please help!

**Comment by ligi** [comment]
just commit the file changed by npx prettier

```
diff --git a/_data/icons/Tettoken256.json b/_data/icons/Tettoken256.json
index b240ffb1..155568a6 100644
--- a/_data/icons/Tettoken256.json
+++ b/_data/icons/Tettoken256.json
@@ -1,8 +1,8 @@
-[
-  {
-    "url": "ipfs://QmYvFVprVdAGJH4iHUCXGEmy7pq8MMfxEjM64SuXutz9qx",
-    "width": 256,
-    "height": 256,
-    "format": "png"
-  }
-]
+[
+  {
+    "url": "ipfs://QmYvFVprVdAGJH4iHUCXGEmy7pq8MMfxEjM64SuXutz9qx",
+    "width": 256,
+    "height": 256,
+    "format": "png"
+  }
+]
```

**Comment by Farid116** [comment]
> just commit the file changed by npx prettier
> 
> ```
> diff --git a/_data/icons/Tettoken256.json b/_data/icons/Tettoken256.json
> index b240ffb1..155568a6 100644
> --- a/_data/icons/Tettoken256.json
> +++ b/_data/icons/Tettoken256.json
> @@ -1,8 +1,8 @@
> -[
> -  {
> -    "url": "ipfs://QmYvFVprVdAGJH4iHUCXGEmy7pq8MMfxEjM64SuXutz9qx",
> -    "width": 256,
> -    "height": 256,
> -    "format": "png"
> -  }
> -]
> +[
> +  {
> +    "url": "ipfs://QmYvFVprVdAGJH4iHUCXGEmy7pq8MMfxEjM64SuXutz9qx",
> +    "width": 256,
> +    "height": 256,
> +    "format": "png"
> +  }
> +]
> ```

Made changes-removed CR LF at the end
Anyway
Error: Process completed with exit code 1.

What am I doing wrong?
