### ISSUE TITLE
lost coins

### ISSUE THREAD

**Issue by ceRStal2a** [ethereum-lists/chains#357]
Hello... I have these coins missing and I would like to get them back..
These coins were on the Metamsk wallet and I wanted to transfer them to the Binance platform, but as it is clear that I made a big mistake, as it is in the picture, and I am new to currency trading.
<img width="476" alt="2021-07-31_14-37-24" src="https://user-images.githubusercontent.com/88234765/127738740-c040055b-44a3-4484-888a-1a4373e24dda.png">

**Comment by ligi** [comment]
wrong repo for this

**Comment by Hlsinclair** [comment]
Hey all. I asked for repo a few months back. Thunder Token made Wallet with
no key and of the ETH does not go across the Bridge it's stuck they per
Thunder Token more money and then it works all of sudden and you own
worthless tokens. I refused now here it is..


0xe373e1AB6Df447cD0b6ae22779F3E8Dd0a288d53

like $13.50 now

**Comment by ceRStal2a** [comment]
Thank you very much. I am grateful for your help and I thank you for your time and effort to help me
Thank you very much and have a nice day
