### ISSUE TITLE
Displaying unkown (wrong) logo for Arthera Chain Testnet

### ISSUE THREAD

**Issue by lperello** [ethereum-lists/chains#3572]
For https://chainlist.org/chain/10243
The logo displayed should be https://ipfs.io/ipfs/QmYQp3e52KjkT4bYdAvB6ACEEpXs2D8DozsDitaADRY2Ak as in the merged PR #3005
which provides
https://github.com/ethereum-lists/chains/blob/master/_data/iconsDownload/QmYQp3e52KjkT4bYdAvB6ACEEpXs2D8DozsDitaADRY2Ak
and as configured in https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-10243.json
But the currently displayed logo is: https://chainlist.org/unknown-logo.png
Is it due to not supporting IPFS hosting for the icon or due to the format of the icon?
Thanks in advance for your help

**Comment by lperello** [comment]
Just checked few other Chains displaying the unkown-logo
It seems that IPFS is not supported
Example: https://chainlist.org/chain/909
The configured logo is the right one, but the displayed one it a default one
https://github.com/ethereum-lists/chains/blob/master/_data/iconsDownload/QmeMa6aw3ebUKJdGgbzDgcVtggzp7cQdfSrmzMYmnt5ywc

**Comment by ligi** [comment]
shows good in our frontends:

![image](https://github.com/ethereum-lists/chains/assets/111600/bd62d0c0-4ac2-48c6-982e-d52a344204ab)

just open the issue in the frontend u use - or better yet not use it

**Comment by lperello** [comment]
@ligi thanks for your help
Will create an issue for the DefiLlama/chainlist
Have a great day
