### ISSUE TITLE
ShortName to ChainID mapping

### ISSUE THREAD

**Issue by pedrouid** [ethereum-lists/chains#359]
It would be great to output a mapping of `shortName` to `chainId` as part of the CI build process for the registry.

This would be useful to use as prefixing of CAIP-10 account identifiers using aliases that could then be queryable through this registry:

```js
eip155:1:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> eth:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb

eip155:10:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> ovm:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb

eip155:56:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> bsc:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb

eip155:100:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> xdai:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb

eip155:137:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> poly:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb

eip155:42161:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> arb:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb

eip155:42220:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb -> celo:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb
```

Currently the registry already ensures unique `shortName` are provided so we can output a JSON that index by it instead so that it can resolve the chainId from these prefix aliases

```js
  eth -> eip155:1

  ovm -> eip155:10

  bsc -> eip155:56

  xdai -> eip155:100

  poly -> eip155:137

  arb -> eip155:42161

  celo -> eip155:42220
  ```

**Comment by ligi** [comment]
Will most likely do this end of the week

**Comment by ligi** [comment]
Just thinking about it a bit more - for the aggregated JSONs there should be no difference right? So what you basically want is the content of _data with different filenames - right?

**Comment by pedrouid** [comment]
Honestly I was thinking way simpler.

CI would output a single aggregated JSON file that maps one string key (shortName) to one string value (CAIP-2 chainId)

If a developer would want more info for the chain then the chainId is enough to find it

**Comment by ligi** [comment]
ah OK - so another json called shortNameMapping.json - also works for me!
