### ISSUE TITLE
Getting icons displayed properly

### ISSUE THREAD

**Issue by neutrinoks** [ethereum-lists/chains#3608]
Hello everybody,

I tried to provide our icon files for Agung and Krest networks via IPFS properly, but so far I was not successful. In the beginning it was hard for me to figure out, how to create a IPFS link that way, that it got accepted by your GitHub actions. Now they got accepted, but will still not be displayed.

Maybe there could be a tutorial or at least a step-by-step instruction chapter on your readme, which contains all the important aspects of setting up a properly working icon file via IPFS?

Regards, Michael

**Comment by ligi** [comment]
this is a problem of the frontends - not of this backend
