### ISSUE TITLE
Fix case-sensitive file names in the repo

### ISSUE THREAD

**Issue by AlicanC** [ethereum-lists/chains#3690]
Currently we have at least two files that cause issues when the repo is cloned in a case-insensitive environment:
`_data/icons/LaChain.json`
`_data/icons/lachain.json`

It would be cool if we fixed these issues and maybe even tried to prevent this from happening later in the future.

**Comment by ligi** [comment]
This is just a windows issue right?

**Comment by AlicanC** [comment]
I'm having this on macOS ATM.

**Comment by ligi** [comment]
They also :man_facepalming: 
If someone wants to deal with this - feel free - I won't. I recommend using a case sensitive FileSystem ..

**Comment by Thaithongvbhp9x** [comment]
🗡️

**Comment by vegeta321311** [comment]
#AA00FF

**Comment by asggWa** [comment]
Es fireofx en descargas?
Será que char está tratando de usar 32 bites y no entra el entrecomillado simple para cadena ...
Me está pasando eso. En este caso a mi conmigo solo.

**Comment by M13551977** [comment]
- [ ]
