### ISSUE TITLE
How do I add my chain? 

### ISSUE THREAD

**Issue by Nexsuperne101** [ethereum-lists/chains#3753]
Hi, complete noob here.

I created this, but I have no idea where to put it.

name": "Chadchain Mainnet", "chain": "CHAD", "rpc": [ "chad2chain.org", "" ], "faucets": [], "nativeCurrency": { "name": "Chad", "symbol": "CHAD", "decimals": 18 }, "features": [{ "name": "EIP155" }, { "name": "EIP1559" }], "infoURL": "chadchain.org", "shortName": "chad", "chainId": 57918080, "chad2chain.org": 57918080, "icon": "chad", "explorers": [{ "name": "etherscan", "url": "chadscan.org", "icon": "chadscan", "standard": "EIP3091"

Any help is very much appreciated!!

Thanks, Nex

**Comment by ligi** [comment]
https://github.com/ethereum-lists/chains/blob/master/README.md

**Comment by Nexsuperne101** [comment]
I read that. It's as clear as mud. Have you got a step by step guide please?
