### ISSUE TITLE
Chain id and filename mismatch issue

### ISSUE THREAD

**Issue by Osman-Mahmood** [ethereum-lists/chains#3802]
Hi we have chain id of 195(testnet) and 71(mainnet) but the filename with this chain id already exists with the name of eip155-195.json eip155-71.json 
the problem our chain id of 71 is for mainnet and someone chain id 71 is for testnet.
but unfortunately our file name is also same and we can't create with this file name 
please suggest us the solution if we change our filename or something else
thanks

**Comment by Osman-Mahmood** [comment]
https://chainlist.org/
and the chain id with 71 and 195 is not existing in https://chainlist.org/
but in code it presents and i can't able to make this file name

**Comment by ligi** [comment]
https://github.com/ethereum-lists/chains#collision-management
