### ISSUE TITLE
import from Trezor ethereum networks list

### ISSUE THREAD

**Issue by prusnak** [ethereum-lists/chains#4]
For Trezor we maintain a similar list here: https://github.com/trezor/trezor-common/blob/master/defs/ethereum/networks.json

You might want to add new networks from the list and also add the fields from our list. Except for `blockbook` all of them are not-specific for Trezor and could be useful for everybody.

Feel free to ask for details if needed.

**Comment by ligi** [comment]
thanks - very helpful!

**Comment by pedrouid** [comment]
Thanks a lot! I added some chains from that list, I will revisit this about the other fields.

**Comment by ligi** [comment]
closed via #117
