### ISSUE TITLE
one json per network

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#40]
the json containing all chains will grow hard to edit at some point. in the ethereum-lists/tokens repo we switched to one token json files then that afterwards get assembled by the ci to a single json file.
What do you think @bmann @pedrouid

**Comment by pedrouid** [comment]
Seconded 👍

**Comment by bmann** [comment]
This is in fact easier and would mean source can be Markdown that generates pages, but single JSON was originally easier to edit. 

I can take a crack at doing a sample of the easiest way to do this.

**Comment by ligi** [comment]
@bmann did you work on this already? Otherwise I would do that soon - kind of need that now

**Comment by ligi** [comment]
#25 is kind of a dependency for this. Would really love to have filenames like:

<chainID>.json

and this does not work if there are duplicate chainIDs

will comment in #25 to push to solve this one

**Comment by pedrouid** [comment]
I've submitted a PR (#44) to fix this and unblock this issue
