### ISSUE TITLE
[New Chain / Network]

### ISSUE THREAD

**Issue by Ameer1062** [ethereum-lists/chains#402]
> Fill out the following to add your chain / network id, OR propose a Pull Request making your edits to the ```_data/chains.json``` file directly

```
{
  "name": "Dollar Mainnet",
  "shortName": "nusd",
  "chain": "NUSD",
  "network": "mainnet",
  "chainId": 1,
  "networkId": 1,
  "rpc": ["https://mainnet.infura.io"],
  "faucets": [],
  "infoURL: "https://usdnetwork.org",
  "nativeCurrency": {"name":"Nusd","symbol":"NUSD","decimals":18}
}
```

**Comment by ligi** [comment]
Can you elaborate on this?

**Comment by Ameer1062** [comment]
Am trying to design a new network. Pre-minted, POS, native NUSD (NEWUSD) pays for gas hence gas fee never fluctuates. Coin supply release based on backing of bank deposit, for each fiat purchase par to USD. Pls. feel free  to contribute.
