### ISSUE TITLE
Bipolar api

### ISSUE THREAD

**Issue by Myahr208** [ethereum-lists/chains#4163]
¹⁰⁴  ¹¹⁶  ¹¹⁶  ¹¹²  ¹¹⁵  ⁵⁸  ⁴⁷  ⁴⁷  ¹⁰³  ¹⁰⁵  ¹¹⁶  ¹⁰⁴  ¹¹⁷  ⁹⁸  ⁴⁶  ⁹⁹  ¹⁰⁹  ⁴⁷  ⁹⁷  ¹⁰⁹  ¹⁰⁵  ¹⁰⁸  ⁹⁷  ⁹⁸  ¹¹⁵  ⁴⁷  ⁹⁹  ¹¹⁴  ¹²¹  ¹¹²  ¹¹⁶  ⁴⁵  ¹²⁰  ⁹⁹  ¹⁰⁴  ⁹⁷  /ᵍᵉᵗᵀᵒᵏᵉⁿᴵⁿᶠᵒ/⁰ˣᶠ³ᵈᵇ⁵ᶠᵃ²ᶜ⁶⁶ᵇ⁷ᵃᶠ³ᵉᵇ⁰ᶜ⁰ᵇ⁷⁸²⁵¹⁰⁸¹⁶ᶜᵇᵉ⁴⁸¹³ᵇ⁸?ᵃᵖⁱᴷᵉʸ=ᶠʳᵉᵉᵏᵉʸ ʲᵉʳⁱᵐⁱᵃʰ ᴿᵃˢᵐᵘˢˢᵉⁿ ¹⁰³  ¹¹⁴  ⁴⁷  ⁹⁸  ¹⁰⁸  ⁹⁸  ⁴⁷  ¹¹⁷  ¹¹²  ⁹⁷  ¹¹⁶  ⁴⁵  ¹²⁰  ⁹⁹  ¹⁰⁴  ⁹⁷  ¹⁰³  ⁴⁵  ¹¹⁵  ¹¹⁴  ¹¹⁸  ¹⁰⁵  ⁹⁹  ⁴⁷  ¹²⁰  ⁹⁷  ¹⁰⁹  ¹¹²  ¹⁰⁸  ³⁷  ⁵⁰  ⁷⁰  ⁹⁹  ¹⁰²  ¹⁰⁵  ¹⁰³  ⁴⁶  ¹⁰⁶  ¹¹⁵  ³⁵  ⁷⁶  ⁴⁹  ⁴⁵  ⁷⁶  ⁵⁰  ⁵⁷ ʲᵉʳⁱᵐⁱᵃʰ ᴿᵃˢᵐᵘˢˢᵉⁿ ʲʲʳⁿᵉʷ¹⁰⁰@ᵍᵐᵃⁱˡ.ᶜᵒᵐ

**Comment by ara745** [comment]
Very gooooooooood
