### ISSUE TITLE
Network ICON are not displayed on chainid.network

### ISSUE THREAD

**Issue by icodezjb** [ethereum-lists/chains#4179]
1. https://chainid.network/ : not update
![image](https://github.com/ethereum-lists/chains/assets/8869892/ba2be877-f021-4182-8902-03fde9935a36)

2. https://chainlist.wtf/: has updated
![image](https://github.com/ethereum-lists/chains/assets/8869892/a5804ef4-b492-4ca6-9680-19d542fd0634)

**Comment by ligi** [comment]
@FrederikBolding do you have an idea? Is there new commits on https://chainlist.wtf that enable it there and not here?

**Comment by FrederikBolding** [comment]
@ligi Apologies, I forgot to update the submodule. PR here: https://github.com/ethereum-lists/chains/pull/4194

**Comment by ligi** [comment]
@FrederikBolding no worries - thanks!

**Comment by ligi** [comment]
this seems to fix the issue
