### ISSUE TITLE
Remove specific URL address from existing chain

### ISSUE THREAD

**Issue by mnedelchev-vn** [ethereum-lists/chains#4245]
Hi, so this is the **[eip155-245022926.json](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-245022926.json)** where I want to remove specific URL, because it's not supported anymore, but when I open the json file I don't see the url included there. Where I can make the PR to remove specific URL? The URL that has to be removed is https://proxy.devnet.neonlabs.org/solana, can be found **[here](https://chainlist.org/?search=neon+evm+devnet&testnets=true)**.

**Comment by ligi** [comment]
URL not in json

**Comment by mnedelchev-vn** [comment]
@ligi then would you please share with me where I have to remove this URL?

**Comment by mnedelchev-vn** [comment]
@ligi ?
