### ISSUE TITLE
LiquidLayer Network ICON are not displayed

### ISSUE THREAD

**Issue by LiquidLayerOff** [ethereum-lists/chains#4257]
1. https://chainid.network/ : not update
![image](https://github.com/ethereum-lists/chains/assets/149963527/25bc5af6-35bc-4139-bf56-f7273df982c0)

2. https://chainlist.wtf/ : not show network
![image](https://github.com/ethereum-lists/chains/assets/149963527/f0ac449a-84fd-49b5-9b3e-8f162bb3141a)

**Comment by ligi** [comment]
@FrederikBolding do you maybe have an idea here?

**Comment by FrederikBolding** [comment]
Chainlist.wtf had a CI issue that prevented it from automatically building a new site. This should be fixed now. I see LiquidLayer on both sites.

With regards to the icon missing it may be a failed IPFS download during build. Not sure how we can improve that @ligi
