### ISSUE TITLE
Eip155-713 - VRCSCAN Mainnet

### ISSUE THREAD

**Issue by Osman-Mahmood** [ethereum-lists/chains#4307]
Hi thanks for adding our chain into evm list but our logo is not well displayed as you can see in screenshot i added ipfs correct link. [ { "url": "ipfs://QmasMkZJ6m7y77fgY6SooNnrH3Y4a3vVYNDWe9T3KusxeU", "width": 512, "height": 512, "format": "png" } ]
<img width="1005" alt="Screenshot 2024-02-06 at 10 58 47 AM" src="https://github.com/ethereum-lists/chains/assets/95136401/0178226e-9aaa-489b-bde2-e4ae5136636c">
Please help us to solve it and mark our mistake

**Comment by Osman-Mahmood** [comment]
Here is pinata ipfs link of our coin image
https://pink-blank-alpaca-711.mypinata.cloud/ipfs/QmasMkZJ6m7y77fgY6SooNnrH3Y4a3vVYNDWe9T3KusxeU?pinataGatewayToken=dHz3Iok6rd6lbPYxWj_UUv_3U_KRZ88T4jxUCdSSFzcoYL5J_Wri9UQxHo143OP2

**Comment by ligi** [comment]
it shows up fine

![image](https://github.com/ethereum-lists/chains/assets/111600/e432cfa0-45fb-4dcb-969f-1b79f84401f5)
