### ISSUE TITLE
Cannot see official results on website regarding PR #4188

### ISSUE THREAD

**Issue by James-Chen1** [ethereum-lists/chains#4333]
Chain ID: 2024
RPC: https://saturn-rpc.swanchain.io/
Name: Swan Saturn

Hi, I was just wondering why we can't see the results of the merge on the main website.
Also, could you please change the details of our change from the mainnet to what I wrote above, which is our testnet?

**Comment by ligi** [comment]
this PR is not from you and about a different chain: https://github.com/ethereum-lists/chains/pull/4188

**Comment by ligi** [comment]
guess this is void seeing https://github.com/ethereum-lists/chains/pull/4339
