### ISSUE TITLE
Metamask warning when adding Wethio network details

### ISSUE THREAD

**Issue by wethioproject** [ethereum-lists/chains#4423]
Hi team, we have our own blockchain - Wethio Blockchain - running from June 2020, following are the details about our blockchain network -
Docs - https://docs.wethio.io
Wallet - https://wallet.wethio.io
Explorer - https://explorer.wethio.io

Our network RPC details are as follows
chain id - 78
rpc url - https://rpc.wethio.io

currency symbol - ZYN

In the latest release of metamask we are facing an issue where in our network is getting marked as Spam (pic attached), because the chain id 78 is linked with the PrimusMoney blockchain on https://chainid.network/. We contacted Metamask for the issue and they have asked us to contact with your team.

![Skype_Picture_2024_01](https://github.com/ethereum-lists/chains/assets/47103225/60f88fa9-f1ca-435f-bc20-044c96424033)

When we set up our mainnet blockchain network, we checked and did not find any other network with chain id 78, and hence went with that chainId. Even as of today, it is difficult to find any info about the PrimusMoney network like RPC or blockchain details. So, we request you to add our network on the chains website so that the above metamask issue can be resolved.

Our blockchain network is also integrated on Ledger devices, (Pull Request detail - https://github.com/LedgerHQ/app-ethereum/pull/289) and we are already registered on the slips repository at - https://github.com/satoshilabs/slips/

**Comment by ligi** [comment]
their RPC seems to be active and still produces blocks: https://ethnode.primusmoney.com/mainnet

this is our collision policy: https://github.com/ethereum-lists/chains?tab=readme-ov-file#collision-management

**Comment by wethioproject** [comment]
Hello
Thanks for the update I don’t think their project I still active , we have
a big community and the message in metamask affect our reputation we should
have a solution for the issue.
Best

**Comment by ligi** [comment]
the RPC is still producing blocks - ask them to stop it or mark their chain deprecated - then you can add yours - currently this is not possible with their chain being active.

**Comment by ligi** [comment]
you should have red: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md and added your chain here earlier.

**Comment by wethioproject** [comment]
We contact the project team , but there is no answer from their side

**Comment by ligi** [comment]
ccing @fbaud who added the chain here: https://github.com/ethereum-lists/chains/pull/187

**Comment by fbaud** [comment]
@wethioproject You did not contact us and we are still using this chain.

We pushed the chain id 78 almost 3 years ago. Either you should have checked chain ids before starting your own chain and you must accept that coming late means taking a free chain id. Or you must accept not being accepted by Metamask (which endorsed the forward looking intent of this repo).

@ligi Thx for the ccing

**Comment by ligi** [comment]
@fbaud thanks for chiming in

**Comment by wethioproject** [comment]
Hello @fbaud <https://github.com/fbaud>, thanks for your message, we sent
you an email on ***@***.***, you can check your spam, and for
our chain it s already started from Juin 2020, it means oldest than your
chain, we did never have this problem on metamask.
@ligi <https://github.com/ligi>  so actually what is the solution for this
problem, as we have already big community behind the project and we can not
accept having such message.

Thanks

**Comment by wethioproject** [comment]
We can not change the chain id as our project running since 2020 and we
have more than 30k users using our rpc

**Comment by wethioproject** [comment]
Our blockchain is older than their blockchain , so minimum you have to
change the error message in metamask, or manage the collision with another
way , our project started in 2020, you should check community for every
project and impact of project in crypto industry to give chain id priority

**Comment by ligi** [comment]
You did not read the documentation (EIP155) and did not register your chainId. So the fault is on your side. We will not run a popularity contest. Our collision policy is clear: the first one registering a chainId gets the chainId.

**Comment by wethioproject** [comment]
@fbaud <https://github.com/fbaud> you still using your solution?

Best Regards,

**Comment by fbaud** [comment]
@wethioproject see my previous response, we are still using this chain and have several workflows relying on it. We do use Metamask in some of them.

**Comment by wethioproject** [comment]
@fbaud <https://github.com/fbaud> please check your email i v sent you an
email on ***@***.***

Le mar. 27 févr. 2024 à 10:55, Frederic Baud ***@***.***> a
écrit :
