### ISSUE TITLE
pulsechain fails to add to metamask

### ISSUE THREAD

**Issue by porkybalboa** [ethereum-lists/chains#443]
seems there is a variable left out in the rpc url. please see screenshot

onclick it drops an error https://i.imgur.com/Nnl2vbA.png

**Comment by ligi** [comment]
I do not really see a difference of chain 369 to the other ones - do the other ones work for you?

**Comment by porkybalboa** [comment]
see my screenshot in the bottom left corner, there is a "v1" and $ variable in the url which triggers the error in adding to metamask
correct rpc is simply
https://rpc.mainnet.pulsechain.com
https://rpc.testnet.pulsechain.com

without any wonky paths added.

**Comment by porkybalboa** [comment]
also explorer links are missing on both PULSE entries. but pulse-mainnet is not online yet anyway.

**Comment by ligi** [comment]
@3commascapital can you check? You submitted these RPCs in your PR

**Comment by 3commascapital** [comment]
this should be fixed as of #981, #982
