### ISSUE TITLE
Chain icon missing. 

### ISSUE THREAD

**Issue by BitrockChain** [ethereum-lists/chains#4506]
Hi have a great today, Chainlist team.

one question why the logo in chainlist is not showing. some of the icons that I see refer to defillama. but the bitrock icon is not updated. Is there anything I need to do to update the icon?

Thanks 🤍

<img width="592" alt="Screenshot 2024-03-08 at 21 03 52" src="https://github.com/ethereum-lists/chains/assets/138885902/d31f5993-0519-4973-b279-68c19bb5012a">

Chainlist:
https://chainlist.org/chain/7171

Defillama: 
https://defillama.com/chain/Bitrock
https://icons.llamao.fi/icons/chains/rsz_bitrock

**Comment by ligi** [comment]
open this issue here: https://github.com/DefiLlama/chainlist
