### ISSUE TITLE
Defi Oracle adding to Metamask

### ISSUE THREAD

**Issue by kitykat52** [ethereum-lists/chains#4512]
My Metamask connection to defi Oracle stopped working.  I tried to reinstall it and when i go to approve it I get an error message says it cannot connect to custom network.  I have heard from others they might be working on an upgrade but it has been down for over a week or more.  Any help would be greatly apricated.

**Comment by refref1991** [comment]
Konuyu tam açıklar mısın dostum nerelisin öncelikle türk müsün? Telefondan
konuşalım bana konuyu tam olarak açıkla ayrıca sana bir teklifte
bulunacağım herkese söyledim kısa dönemde büyük paralar kazanmak isteyenler
beni bulsun eşin dostun komşun herkese söyle vereceğim tavsiyeleri yatırım
şartlarını uygularsan hiç kimseyle işin olmadan kısa sürede 99999$$$$
parayı bulursun ben 3 aydır kripto para işine girdim ama neler neler yaptım
eski coin cüzdanları alıyorum içini boşaltıyorum sağlam güvenilir cüzdan
adresime aktarıyorum sana da yardımcı olurum bildiğim öğrendiğim kadarıyla
görüşmek dileğiyle hoşçakalın

10 Mar 2024 Paz 18:37 tarihinde kitykat52 ***@***.***> şunu
yazdı:
