### ISSUE TITLE
[](url)

### ISSUE THREAD

**Issue by Alkhatri77** [ethereum-lists/chains#4514]
[](url)

_Originally posted by @Alkhatri77 in https://github.com/trustwallet/trust-web3-provider/issues/507#issuecomment-1979519655_

**Comment by tilemanrenovations** [comment]
R24MQJM7227BHSG

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Alkhatri77 ***@***.***>
Sent: Sunday, March 10, 2024 5:25:45 PM
To: ethereum-lists/chains ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ethereum-lists/chains] [](url) (Issue #4514)


<url>

Originally posted by @Alkhatri77<https://github.com/Alkhatri77> in trustwallet/trust-web3-provider#507 (comment)<https://github.com/trustwallet/trust-web3-provider/issues/507#issuecomment-1979519655>
