### ISSUE TITLE
Icon missing on Chain 96 Bitkub Chain 

### ISSUE THREAD

**Issue by ntpbright** [ethereum-lists/chains#4518]
Hi have a good today, Chainlist team.

Icon doesn't show on chain details page
https://chainlist.org/chain/96

<img width="1394" alt="image" src="https://github.com/ethereum-lists/chains/assets/17776828/8593c15d-3e2b-4f73-a5c8-8730249259d1">

It's should be https://ipfs.io/ipfs/QmYFYwyquipwc9gURQGcEd4iAq7pq15chQrJ3zJJe9HuFT this logo

This is JSON that already merged into main branch
Link EIP155
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-96.json
Link Icon
https://github.com/ethereum-lists/chains/blob/master/_data/icons/bkc.json
I'm think it's should link from icon file name to key 'icon' in JSON right?

If I do anything wrong please suggest me.
I'll fix immediately.

**Comment by ligi** [comment]
Icon is shown on our site:

![image](https://github.com/ethereum-lists/chains/assets/111600/6c940208-5271-4512-a99d-290916f1eb7b)

ask them what is wrong on their site.

**Comment by ntpbright** [comment]
@ligi sorry how to contract them
