### ISSUE TITLE
how to add my json file to the chainlist.

### ISSUE THREAD

**Issue by Nexsuperne101** [ethereum-lists/chains#4597]
Good afternoon. I'm trying to add new chain details to the list, but it's my first time here, and I am struggling to make any sense of what I'm supposed to do. I'm trying to get the code below added . Can anyone please point me in the right direction. Be gentle, I'm not a coder!! 
Many thanks, Nex

{
  "name": "ChadChain",
  "title": "ChadChain Mainnet",
  "chain": "ChadChain",
  "icon": "ChadChain",
  "rpc": [
    "https://chad2chain.org/"
  ],
  "nativeCurrency": {
    "name": "CHAD",
    "symbol": "CHAD",
    "decimals": 18
  },
  "infoURL": "https://chadchain.org/",
  "shortName": "chad",
  "chainId": 97912060,
  "networkId": 97912060,
  "slip44": 1,
  "explorers": [
    {
      "name": "chadchain",
      "url": "https://chadscan.org/",
      "standard": "EIP3091"
    }
  ]
}

**Comment by ligi** [comment]
submit a PR

**Comment by Nexsuperne101** [comment]
how? I tried that. It keeps saying about nothing to compare with?
