### ISSUE TITLE
Getting formatting issue

### ISSUE THREAD

**Issue by Karthigasrini** [ethereum-lists/chains#4868]
Hi,
Always getting formatting error in icons/json file. How to solve this? Tried many times

![image](https://github.com/ethereum-lists/chains/assets/30004506/f2632a3b-f042-4827-b168-e32acce26c81)

**Comment by ligi** [comment]
run npx prettier --write _data/*/*.json`

**Comment by ligi** [comment]
`npx prettier --write _data/*/*.json``

**Comment by ligi** [comment]
`npx prettier --write _data/*/*.json`
