### ISSUE TITLE
Bankcoin Cash Mainnet

### ISSUE THREAD

**Issue by ansarul543** [ethereum-lists/chains#4881]
{
  "name": "Bankcoin Cash",
  "chain": "Bankcoin Cash",
  "rpc": ["https://rpc.bankcoincash.org"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Bankcoin Cash",
    "symbol": "BKC",
    "decimals": 18
  },
  "infoURL": "https:/bankcoincash.org",
  "shortName": "bankcoincash",
  "chainId": 1994,
  "networkId": 1994,
  "explorers": [
    {
      "name": "BKC Block Explorer",
      "url": "https://scan.bankcoincash.org",
      "standard": "none"
    }
  ]
}

**Comment by IGhottem** [comment]
Hello

**Comment by LizetteO** [comment]
hello
