### ISSUE TITLE
Koco Coin Mainnet

### ISSUE THREAD

**Issue by ansarul543** [ethereum-lists/chains#4882]
{
  "name": "Kococoin",
  "chain": "Kococoin",
  "rpc": ["https://rpc.kococoin.com"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Koco Coin",
    "symbol": "KOCO",
    "decimals": 18
  },
  "infoURL": "https:/kococoin.com",
  "shortName": "kococoin",
  "chainId": 1995,
  "networkId": 1995,
  "explorers": [
    {
      "name": "Koco Block Explorer",
      "url": "https://kocoscan.com",
      "standard": "none"
    }
  ]
}

**Comment by ligi** [comment]
submit a PR

**Comment by ansarul543** [comment]
How to submit PR. We have tried gradlew run.  Its falied
