### ISSUE TITLE
Adding Parex Network

### ISSUE THREAD

**Issue by parexexchange** [ethereum-lists/chains#4996]
Hi,
We can get our icon with 
ipfs get QmSPD3QcjFJL2KpYRnNDxa8Xg5rcSgPugG9kcBBNeavVKi 
and we can download it from 
https://ipfs.io/ipfs/QmSPD3QcjFJL2KpYRnNDxa8Xg5rcSgPugG9kcBBNeavVKi
please rerun the script?

**Comment by ligi** [comment]
fix the other err

**Comment by parexexchange** [comment]
I fixed the parexmain.json to first working state, can you please rerun the script, but  https://cloudflare-ipfs.com still does not workin but https://ipfs.io/ipfs/QmSPD3QcjFJL2KpYRnNDxa8Xg5rcSgPugG9kcBBNeavVKi  is working

**Comment by parexexchange** [comment]
I fixed the other err but it still tries to download from cloudflare-ipfs.com

  if [[ "${CHANGED_ICON_BLOBS[*]} " =~ "_data/iconsDownload/$IPFS_HASH " ]]; then
        TARGET_FILE="_data/iconsDownload/$IPFS_HASH"
      else
        echo "Trying to download the image..."
        TARGET_FILE=icon
        curl -Lo icon "https://cloudflare-ipfs.com/ipfs/$IPFS_HASH" 2>/dev/null
      fi
