### ISSUE TITLE
[New Chain / Network]

### ISSUE THREAD

**Issue by juan21232** [ethereum-lists/chains#50]
> Fill out the following to add your chain / network id, OR propose a Pull Request making your edits to the ```_data/chains.json``` file directly

```
{
  "name": "Ethereum Mainnet",
  "short_name": "eth",
  "chain": "ETH",
  "network": "mainnet",
  "chain_id": 1,
  "network_id": 1,
  "rpc": ["https://mainnet.infura.io"]
}
```

**Comment by ligi** [comment]
?

**Comment by juan21232** [comment]
Por que ami sime urge retirar mis fondos

**Comment by juan21232** [comment]
Mire la verdad yono se como sele ase poreso yo quiero quebñ ustedes me
ayuden a que melo depositen ami cuenta
