### ISSUE TITLE
Frontend update

### ISSUE THREAD

**Issue by brianDahlin** [ethereum-lists/chains#5002]
Hey there! Guys pushed updates 5 days ago to the branch and you performed a merge with the master branch. When approximately will the new build be deployed to the frontend?

**Comment by ligi** [comment]
directly - what are you missing?

**Comment by brianDahlin** [comment]
@ligi 
Atleta testnet - i have changed to Atleta olympia. Also added new rpc

**Comment by ligi** [comment]
![image](https://github.com/ethereum-lists/chains/assets/111600/c5f10eb4-4c8e-44ef-97cb-cd1c87ba1062)

**Comment by brianDahlin** [comment]
![image](https://github.com/ethereum-lists/chains/assets/108185707/d1b9f820-5d86-4fd1-90a7-8d4daff8d14d)

@ligi

**Comment by ligi** [comment]
3rd party website

**Comment by brianDahlin** [comment]
Got it. Thanks 🫡
