### ISSUE TITLE
Not success merge new icon

### ISSUE THREAD

**Issue by bonchoCorp** [ethereum-lists/chains#5068]
https://github.com/ethereum-lists/chains/pull/3304
@ligi
Hi!
A merge was made, but the entire flow did not go through and, accordingly, the icon did not change.

**Comment by ligi** [comment]
![image](https://github.com/ethereum-lists/chains/assets/111600/b1949daa-01a4-4a52-b8be-136c558d1496)

seems correct to me

**Comment by bonchoCorp** [comment]
Yes, https://chainid.network/ has the correct icon. But for https://chainlist.org/chain/1231 - no. Should it be remembered somewhere else?

**Comment by ligi** [comment]
3rd party website - ask them
