### ISSUE TITLE
Avax

### ISSUE THREAD

**Issue by Bumblebee9999** [ethereum-lists/chains#512]
> Fill out the following to add your chain / network id, OR propose a Pull Request making your edits to the ```_data/chains.json``` file directly

```
{
  "name": "Ethereum Mainnet",
  "shortName": "eth",
  "chain": "ETH",
  "network": "mainnet",
  "chainId": 1,
  "networkId": 1,
  "rpc": ["https://mainnet.infura.io"],
  "faucets": [],
  "infoURL: "https://ethereum.org",
  "nativeCurrency": {"name":"Ether","symbol":"ETH","decimals":18}
}
```

**Comment by nanmcpe** [comment]
> Hello! How to connect AVAX to METAMASK?

Go to https://chainlist.org/ and search for Avalanche

**Comment by Irishgrizz** [comment]
> Hello! How to connect AVAX to METAMASK?

**Comment by Irishgrizz** [comment]
Why would you want to put your avalanche and your MetaMask account why wouldn't you just get an avalanche wallet or almost any other wallet for that matter I don't know who asked this question from my platform Whoever it was that stole my identity and thought it would be a good idea to take anything from me I sure hope you enjoy what's coming next and while you're enjoying your life behind bars I'll be on my boat fishing you picked the wrong redneck Enjoy I will

**Comment by Irishgrizz** [comment]
I don't know maybe you can ask Bubba while you're in prison how to put your avalanche into your MetaMask wallet in the meantime I just keep it in my Gnosis safe Maybe when you get out in 20 years you can think about how you're gonna take it from me again I'm always down for another twirl

**Comment by Irishgrizz** [comment]
Hello how do I report bumblebee9999 aka Brandi johnson for being in my personal accounts with out permission and for giving admin control to nicki Christiansen on that email account
