### ISSUE TITLE
Register a private validium chain without publicly accessible RPC

### ISSUE THREAD

**Issue by minhbsq** [ethereum-lists/chains#5191]
I want to register a Layer 2 chain that is powered by ZkSync. The chain is a private Validium chain and the there's only one operator that can access the RPC server (ie: RPC is not open to public). All user operations needs to be proxied via the operator.

The point of registering this chain in is that we can make sure the user can sign the transaction with the right chainID. My questions are:
1. Does this make sense to register it in the first place?
2. If yes, can we leave the RPC endpoints as empty?

Thank you for your time in answering these questions

**Comment by valipanahi** [comment]
Hello, do the right thing and I agree

در تاریخ پنجشنبه ۳۰ مه ۲۰۲۴،‏ ۷:۵۴ Minh Pham ***@***.***>
نوشت:

**Comment by minhbsq** [comment]
@ligi The reason is that we operate under a trustless model, but not permissionless since we are building a regulated exchange and there are regulations that we need to follow regarding Anti Money Laundering. A permissionless model would mean that anyone could interact with our chain and bridge money in, which could violate our AML policy

**Comment by ligi** [comment]
I am really torn here - on the one hand I strongly believe in permissionless blockchains - on the other hand I do not want chainIDs to collide to not open the door for replay attacks.

**Comment by 777easy** [comment]
I understand I not giving up I been doing this for long time and  didn't
make money with it yet got crypto but still don't know exactly what to do
with it  because most of the time I am trying to fight hackers to keep my
suff safe and why I didn't make money yet I got a lot of people that want
to try it but scared of the process that it takes to make money at it I
told them that I am having trouble with it because I am getting hacked if
it wasn't for that I would be good but nothing in this world is easy if it
was everybody would be doing it but harder it is more rewarding

shane Lassere

**Comment by Chator1** [comment]
0x84e8277c938102f42FC2D9625Fc75049A86c99Ae

**Comment by Sintayew4** [comment]
#5191

**Comment by Chator1** [comment]
ارغب في تسجيل سلسله #5191

 وترك نقاط النهاية

**Comment by tuanfish** [comment]
0x93602868D7603097C56321599Ec0b65b91Cb7367

**Comment by minhbsq** [comment]
@ligi sorry I haven't replied sooner. I have the opinion that there shouldn't be a one size fit all model, and there's a spectrum between trustless - permissionless that can cater to the different use cases. Should this repo be open to that vision too?

**Comment by nnlgsakib** [comment]
> I want to register a Layer 2 chain that is powered by ZkSync. The chain is a private Validium chain and the there's only one operator that can access the RPC server (ie: RPC is not open to public). All user operations needs to be proxied via the operator.
> 
> The point of registering this chain in is that we can make sure the user can sign the transaction with the right chainID. My questions are:
> 
> 1. Does this make sense to register it in the first place?
> 2. If yes, can we leave the RPC endpoints as empty?
> 
> Thank you for your time in answering these questions

bro seriously?

**Comment by kennet31526** [comment]
It was stolen by krypton.so

**Comment by Mohmmaa** [comment]
R
