### ISSUE TITLE
Etherlink Icon is not displayed

### ISSUE THREAD

**Issue by devon-n** [ethereum-lists/chains#5362]
On the chain list website the etherlink icons are not loaded properly.

<img width="691" alt="Screenshot 2024-06-25 at 5 50 23 PM" src="https://github.com/ethereum-lists/chains/assets/65629705/e24a617b-2552-4180-9349-a2889876cdaa">

They are configured correctly
[Mainnet](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-42793.json)
<img width="591" alt="Screenshot 2024-06-25 at 5 52 39 PM" src="https://github.com/ethereum-lists/chains/assets/65629705/97a46e00-4637-4248-9588-735ef87ca1a8">

[Testnet](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-128123.json)
<img width="660" alt="Screenshot 2024-06-25 at 5 52 11 PM" src="https://github.com/ethereum-lists/chains/assets/65629705/d0378f9b-9d64-4c3b-be55-331a3866dbbe">

[etherlink.json](https://github.com/ethereum-lists/chains/blob/master/_data/icons/etherlink.json)
<img width="746" alt="Screenshot 2024-06-25 at 5 53 15 PM" src="https://github.com/ethereum-lists/chains/assets/65629705/47517241-9b3c-4b7a-a609-4d3f0fc78d8b">

**Comment by ligi** [comment]
![image](https://github.com/ethereum-lists/chains/assets/111600/af535df2-cecf-4ac6-a063-5ad09580f808)
 works perfectly on our site - ask the other site why they fail
