### ISSUE TITLE
Mumbai Matic RPC Failing

### ISSUE THREAD

**Issue by johnnyshankman** [ethereum-lists/chains#544]
This network does not work, whether added through the app or manually in MM.

```
Request for method 'eth_chainId on https://rpc-mumbai.matic.today failed
```

I believe the RPC is getting too many requests and chain ID is not coming back.

We should consider trying a different Mumbai provider.

**Comment by ligi** [comment]
do you have another mumbai provider in mind?

**Comment by ligi** [comment]
actually there are more RPCs in the list - so I just remove this one - also fails consistently for me.
