### ISSUE TITLE
Icon validation keeps failing

### ISSUE THREAD

**Issue by divechan** [ethereum-lists/chains#5591]
Here is the output from the check:

Run set -euo pipefail
Checking icon _data/icons/railsnetwork.json
Trying to download the image...
Expected width 200, got null
Expected height 200, got null
Expected type png, got html
Checking icon _data/icons/railsnetworktestnet.json
Trying to download the image...
Expected width 200, got null
Expected height 200, got null
Expected type png, got html
Error: Process completed with exit code 1.

Here is my metadata of the file uploaded to IPFS:

ExifTool Version Number : 12.92
File Name : Testnet.png
Directory : E:/GitHub/brandkit/SVGs
File Size : 42 kB
File Modification Date/Time : 2024:07:26 23:25:28-04:00
File Access Date/Time : 2024:07:27 18:26:54-04:00
File Creation Date/Time : 2024:07:26 23:25:28-04:00
File Permissions : -rw-rw-rw-
File Type : PNG
File Type Extension : png
MIME Type : image/png
Image Width : 200
Image Height : 200
Bit Depth : 8
Color Type : RGB with Alpha
Compression : Deflate/Inflate
Filter : Adaptive
Interlace : Noninterlaced
Pixels Per Unit X : 11811
Pixels Per Unit Y : 11811
Pixel Units : meters
XMP Toolkit : Adobe XMP Core 9.1-c002 79.dba3da3, 2023/12/13-05:06:49
Creator Tool : Adobe Photoshop 25.7 (Windows)
Create Date : 2024:07:26 23:06:44-04:00
Modify Date : 2024:07:26 23:25:25-04:00
Metadata Date : 2024:07:26 23:25:25-04:00
Format : image/png
Color Mode : RGB
Instance ID : xmp.iid:f2a1611e-a12e-ae4a-a63e-4195bb9f5fbd
Document ID : adobe:docid:photoshop:f2970519-7dc5-ce43-8012-60efcdeb398b
Original Document ID : xmp.did:5daea5da-b0ed-e64d-911e-a907b0343c71
History Action : created, converted, saved
History Instance ID : xmp.iid:5daea5da-b0ed-e64d-911e-a907b0343c71, xmp.iid:f2a1611e-a12e-ae4a-a63e-4195bb9f5fbd
History When : 2024:07:26 23:06:44-04:00, 2024:07:26 23:25:25-04:00
History Software Agent : Adobe Photoshop 25.7 (Windows), Adobe Photoshop 25.7 (Windows)
History Parameters : from application/vnd.adobe.photoshop to image/png
History Changed : /
Image Size : 200x200
Megapixels : 0.040

ExifTool Version Number : 12.92
File Name : Mainnet.png
Directory : .
File Size : 53 kB
File Modification Date/Time : 2024:07:27 18:29:41-04:00
File Access Date/Time : 2024:07:27 18:29:41-04:00
File Creation Date/Time : 2024:07:26 23:20:33-04:00
File Permissions : -rw-rw-rw-
File Type : PNG
File Type Extension : png
MIME Type : image/png
Image Width : 200
Image Height : 200
Bit Depth : 8
Color Type : RGB with Alpha
Compression : Deflate/Inflate
Filter : Adaptive
Interlace : Noninterlaced
Pixels Per Unit X : 11811
Pixels Per Unit Y : 11811
Pixel Units : meters
XMP Toolkit : Adobe XMP Core 9.1-c002 79.dba3da3, 2023/12/13-05:06:49
Creator Tool : Adobe Photoshop 25.7 (Windows)
Create Date : 2024:07:26 23:06:44-04:00
Modify Date : 2024:07:26 23:20:32-04:00
Metadata Date : 2024:07:26 23:20:32-04:00
Format : image/png
Color Mode : RGB
Instance ID : xmp.iid:f6daccd4-c748-7540-aef4-13f564a039b7
Document ID : adobe:docid:photoshop:7b910764-2325-9447-bf7f-9d53ab7aa2db
Original Document ID : xmp.did:bfb0f98e-145a-4e42-aeaf-b640d30bfd20
History Action : created, converted, saved
History Instance ID : xmp.iid:bfb0f98e-145a-4e42-aeaf-b640d30bfd20, xmp.iid:f6daccd4-c748-7540-aef4-13f564a039b7
History When : 2024:07:26 23:06:44-04:00, 2024:07:26 23:20:32-04:00
History Software Agent : Adobe Photoshop 25.7 (Windows), Adobe Photoshop 25.7 (Windows)
History Parameters : from application/vnd.adobe.photoshop to image/png
History Changed : /
Exif Byte Order : Big-endian (Motorola, MM)
X Resolution : 72
Y Resolution : 72
Resolution Unit : inches
Y Cb Cr Positioning : Centered
Image Size : 200x200
Megapixels : 0.040

Here is my icon jsons:

railsnetworktestnet:

[
  {
    "url": "ipfs://QmbrFmdmH6RXtLhxPjeKKAxkbyvxaXYjooyZPPA7qFw2HM",
    "width": 200,
    "height": 200,
    "format": "png"
  }
]

railsnetwork:

[
  {
    "url": "ipfs://QmbrFmdmH6RXtLhxPjeKKAxkbyvxaXYjooyZPPA7qFw2HM",
    "width": 200,
    "height": 200,
    "format": "png"
  }
]

I ran gradle + npx prettier on all files successfully.

**Comment by ligi** [comment]
issues are only for bugs - this does not look like a bug & there is no free support - if you want support pay 420DAI to lists.eth
