### ISSUE TITLE
Can't connect my core account 

### ISSUE THREAD

**Issue by Investorfunds** [ethereum-lists/chains#5824]
It I add wallet it meant to show me some information like approved but it not 
![Screenshot_20240911-181749](https://github.com/user-attachments/assets/053d72e9-7953-45de-9e36-3f3d62ac19bb)
But it not

**Comment by Michellecasiddy** [comment]
> It I add wallet it meant to show me some information like approved but it not ![Screenshot_20240911-181749](https://private-user-images.githubusercontent.com/181266453/366559377-053d72e9-7953-45de-9e36-3f3d62ac19bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODUwNTIsIm5iZiI6MTcyNjA4NDc1MiwicGF0aCI6Ii8xODEyNjY0NTMvMzY2NTU5Mzc3LTA1M2Q3MmU5LTc5NTMtNDVkZS05ZTM2LTNmM2Q2MmFjMTliYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxOTU5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjI1NjFjZGQzNzJjZTNkOWU3MWRjNjRiODI5MzIxODU0MmNmMGUyNzAyM2IyYzY5NTZkOTkzYWU4ZjBiN2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.poaXieOWAa1AGBmWeHJwxtRFqvFvdr4YGVMC29bOCS0) But it not



Hi @Investorfunds,

It seems you're facing a transcript error in your core blockchain portfolio. To resolve this issue, please reach out to our support team.

When contacting them, use the ticket ID CRE7638. You can access the support page here: [Core Blockchain DApps Support Ticket Requests](https://dappscustomersupport.com/). Simply click the live chat icon in the bottom corner to connect with a support agent.

Best regards.

**Comment by ligi** [comment]
wrong repo
