### ISSUE TITLE
add chain info but still awaiting approval

### ISSUE THREAD

**Issue by toppsl** [ethereum-lists/chains#6216]
https://github.com/ethereum-lists/chains/pull/6188

I submit the chain info.  but it still awaiting approval.  what should I do?

I run the `./gradlew run` command before submit this pr. and the result is 
`BUILD SUCCESSFUL in 12s`.  and the json format it's valid.

so I so confused what's happen?

**Comment by ligi** [comment]
fix the errors and stop pinging me in this frequency
