### ISSUE TITLE
Astar Shibuya

### ISSUE THREAD

**Issue by aelmanaa** [ethereum-lists/chains#6227]
HI there,

I see that in chainList , 81 doesn't refer to Astar Shibuya (see [here](https://docs.astar.network/docs/build/builder-guides/astar_features/use_hardhat/))

https://github.com/ethereum-lists/chains/blob/6523d3bf24225bf14a17f22b7022c415008c2cec/_data/chains/eip155-81.json#L2

**Comment by ligi** [comment]
https://github.com/ethereum-lists/chains?tab=readme-ov-file#collision-management
