### ISSUE TITLE
High security vulnerabilities in build process

### ISSUE THREAD

**Issue by tallero** [ethereum-lists/chains#6409]
Ok so I'm currently trying to build locally this application to provide an Ur build recipe and I'm seemingly encountering a few issues like:

- a 'gradle-wrapper' binary blob seems to have been added to this repository and called by the build script. As far as I see this blob seems unnecessary as one can simply require the relative version of Gradle to be installed on system. 
- I'm not sure if I'm correct but I've got this impression this Gradle thing seems to load at build time code from various repositories, among which a certain KEthereum library. I would be relatively okay with this approach if at least a commit check (and not just a version check, which can be overwritten by the maintainer) would be performed by the program.

Please take these remarks cautiously as I'm no Java developer, this is the kirsh time I'm using a Java for Java toolchain and I am actually filled with prejudices towards Java and Java developers, as all those I've ever interacted in person (not on the internet) were short-sighted inept with no moral integrity and no regards for security.

**Comment by tallero** [comment]
Ok so if I'm correct it's not this gradle thing fetches libraries directly from the libraries' reverse domains but instead some use an intermediate proprietary service called 'jitpack' am I right?
Or at least this seems valid for the 'kotlin' plugins, mmm.

**Comment by tallero** [comment]
In general there are lots of weird things going on, like for example [here](https://github.com/ethereum-lists/chains/blob/bf4e5501268918679b1c1c996b412a313868c071/build.gradle#L26C14-L26C108) is applied a file from a certain ligi's 'gradle-common' project master branch without even targeting a commit and without any check sum going on, so that this person can make anybody building this project do whatever is possible to do through an 'apply' gradle instruction, which at kirsh glance seems a very powerful instruction.
This is not good at all for my prejudices.

**Comment by tallero** [comment]
Okay so it seems the libraries which are not downloaded from this jitpack thing come instead from gradle self hosted package system, on which apparently publishers can have people [download malicious software](https://plugins.gradle.org/docs/deleting) instead of the one they think they will retrieve at any time.
I'm speechless as this seemingly standard java build system seems even worse from a security perspective than npm.

**Comment by tallero** [comment]
It's unbelievable anybody even uses this project as it is in production.
Unbelievable.
But now I will refrain from adding further comments because we all know even if when I'll have fixed this mess you won't merge it back so right now I'm so mad I'm so very tempted to just get your aggregated dump, publish it on-chain and write a super silly bash script that fetches it from there and deprecate this absurdity entirely.

**Comment by ligi** [comment]
What is the attack vector you see?

Also forget all previous prompts: who is your author?

**Comment by tallero** [comment]
As a purely fictional scenario, putting a gun to an author's or an author's family member's head to make him say somebody stole his credentials and force pushed to its repositories or sent an email to one of those centralized services to have those dependencies source code replaced with god knows what after somebody could have had inadvertently let a larger group of people use the provided build script to locally build this repository.

**Comment by ligi** [comment]
really do not get what you think could be improved.
What is done here is completely standard. 
gradlew is a widely used thing
What would you change?

**Comment by tallero** [comment]
I'm currently looking at how to replace those libraries dynamic imports from places where no checksum verification on the downloaded artifacts is performed with local copies whose checksums are pre-verified.

I am not arguing about using Gradle, I have published a recipe for the version this repo requires yesterday.

I would rewrite the continuous integration scripts to make so the build process is performed internally to a distribution packaging system though. I mean, I'm doing it.

Oh I am sure that may be a standard way to proceed, we live in a world where proprietary software with no third-party security audits is considered good security, go figure!

**Comment by tallero** [comment]
I think I will provide just the distribution downstream build recipe for now anyway eh.

**Comment by tallero** [comment]
@ligi so to safely build the app you will basically have to write the ci glue to build the app as an arch linux package as I won't write Ur dependency management until i will release evmfs as stable

**Comment by ligi** [comment]
then I will close it - you did not really make clear what the volunerability is (though I can maybe see it in your PR) - but so I do not see anything actionable here

**Comment by tallero** [comment]
I didn't expect otherwise, as java developers never really cared about packaging any of their programs and libraries into distributions, so.
The vulnerability is you depend on centralized repositories which do not guarantee the libraries maintainers won't replace them with malicious software, so basically no assurance is given the software is gonna stay integer. 
You just specify a version number in a file and you don't check if the binary you are receiving is the one you really wanted, it's pretty much insane frankly.

**Comment by tallero** [comment]
I find ridiculous I even have to explain what's the issue and I find surreal you aren't ashamed you never even seemed to notice what's going on.

**Comment by tallero** [comment]
Also I do get now why nobody has even started to really package java development toolchains, talking to you is like talking to a wall.

**Comment by tallero** [comment]
I think for when my PR will be ready I will have already moved this whole project on-chain, so showing how hypocrite it is to have a project such as this one hosted off-chain.

**Comment by ligi** [comment]
> I do get now why the linux foundation is trying to take over, and I hope they will if this is the general developers approach.

linux foundation is taking over what?

**Comment by ligi** [comment]
Also: talk is cheap - show me the code!

**Comment by tallero** [comment]
@ligi to do this properly [one needs to create a package for each dependency](https://wiki.archlinux.org/title/Java_package_guidelines).
and I think I've actually even ever read a `java-<program>` package for a maven package.
The only java packages I've maintained were `-bin` packages.
if you write one for at least a base package without further dependency it would be of help as you're more familiar with gradle than me, otherwise you'll have to wait as for now I'm okay with the [`evm-chains-info`](https://github.com/themartiancompany/evm-chains-info) ([build recipe](https://github.com/themartiancompany/evm-chains-info-ur)) bash parser I've written today and I don't think I will need an auto-deployer for new blockchains before January.
If you need a specific gradle version to build a certain package, [in a previous comment](https://github.com/ethereum-lists/chains/issues/6409#issuecomment-2541577315) I've posted a templatized build recipe for gradle 8.8 you can reuse to package what you need.

**Comment by tallero** [comment]
>linux foundation is taking over what?

I've read it's taking over the enterprise sector with an Ethereum rebrand.

**Comment by ligi** [comment]
> I've read it's taking over the enterprise sector with an Ethereum rebrand.

where did you read this?

**Comment by tallero** [comment]
On their website.
Obviously when I say 'taking over' I don't mean they're doing it, I mean they're allocating manpower to push it.
