### ISSUE TITLE
Form network logo not displaying

### ISSUE THREAD

**Issue by arrayofone** [ethereum-lists/chains#6469]
Hi team, I've opened a PR which has been merged for the Form network. I attached a logo which is currently pinned on ipfs through the thirdweb portal. However, the logo is not displaying on [chainlist.org (478)](https://chainlist.org/chain/478). Perhaps I missed a step while making the PR?

Thanks in advance, appreciate any help/guidance!

PR: https://github.com/ethereum-lists/chains/pull/6367

Icon on public gateway: https://ipfs.io/ipfs/QmWrjS43miGAKEzKyNn1YajFn4zG7cDiPiaNHF1gTqKR91

[eip155-478.json](https://github.com/ethereum-lists/chains/blob/a9763da9286c01e5da51dc24b9ac2c08075a7354/_data/chains/eip155-478.json)
```json
{
  "name": "Form Network",
  "title": "Form Network",
  "chain": "form",
  "icon": "form",
  "rpc": ["https://rpc.form.network/http", "wss://rpc.form.network/ws"],
  "features": [
    {
      "name": "EIP155"
    },
    {
      "name": "EIP1559"
    }
  ],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://info.form.network",
  "shortName": "formnetwork",
  "chainId": 478,
  "networkId": 478,
  "explorers": [
    {
      "name": "Form Explorer",
      "url": "https://explorer.form.network",
      "standard": "EIP3091",
      "icon": "form"
    }
  ],
  "faucets": [],
  "parent": {
    "type": "L2",
    "chain": "eip155-1",
    "bridges": [
      {
        "url": "https://bridge.form.network"
      },
      {
        "url": "https://op-bridge.form.network"
      }
    ]
  }
}
```

[icons/form.json](https://github.com/ethereum-lists/chains/blob/master/_data/icons/form.json)
```json
[
  {
    "url": "ipfs://QmWrjS43miGAKEzKyNn1YajFn4zG7cDiPiaNHF1gTqKR91",
    "width": 512,
    "height": 512,
    "format": "png"
  }
]
```

**Comment by ligi** [comment]
It displays on our site:
![image](https://github.com/user-attachments/assets/0820cdd1-5a3a-47d0-a14e-5eb49e9de4b7)

please file a bug with chainlist.org (3rd party service)
