### ISSUE TITLE
[HELP] Token Icon Not Updating Properly After PR Merge on Ethereum Lists

### ISSUE THREAD

**Issue by AndyBoWu** [ethereum-lists/chains#6497]
**Issue Description**

We recently had [this PR](https://github.com/ethereum-lists/chains/pull/6456) merged, and the network is now properly registered on the ethereum-lists repository.

However, we've noticed an issue: the token icon is not updating correctly and still displays the Ethereum icon in some places (refer to the attached screenshot).

For additional context, the icon is defined correctly, following the proper format, size requirements, and hosted on IPFS:

```
[
  {
    "url": "ipfs://bafkreif4spxrmmnq6nymf6waxtr5ku4qjtbho3pvbhjke6td3ezyjzd4ay",
    "width": 256,
    "height": 256,
    "format": "png"
  }
]
```
Could you please investigate this issue and let us know what might be causing it? Thank you!

Tagging @ligi for support.

<img width="947" alt="image" src="https://github.com/user-attachments/assets/c28fc617-ddda-445d-949a-98393cfd6b8f" />

**Comment by ligi** [comment]
looks good on our side ![image](https://github.com/user-attachments/assets/bf2b6800-9e37-4e85-80ad-3bb1a439ea72)
please file the bug in the buggy frontend

**Comment by ROMJAN2185** [comment]
0x033f64d57a0093546833547300ec0169e3cbb643

**Comment by ROMJAN2185** [comment]
1514

**Comment by Affan315** [comment]
[
  {
    "url": "ipfs://bafkreif4spxrmmnq6nymf6waxtr5ku4qjtbho3pvbhjke6td3ezyjzd4ay",
    "width": 256,
    "height": 256,
    "format": "png"
  }
]

**Comment by ogunleye0720** [comment]
@ligi Hi hi. This issue is the same for all Recent PRs. The icon displays properly on chainid.network but doesn't display on chainlist.org.
