### ISSUE TITLE
introduce field baseTokenName

### ISSUE THREAD

**Issue by ligi** [ethereum-lists/chains#66]
I think this could be helpful - I currently actually need it ;-)

**Comment by pedrouid** [comment]
How about we use the same format as the EIP-2015?

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2015.md#example-1

```js
      "nativeCurrency": {
        "name": "xDAI",
        "symbol": "xDAI"
      }
```

**Comment by pedrouid** [comment]
In fact, we should include also the decimals just in case

**Comment by ligi** [comment]
sounds good

**Comment by ligi** [comment]
do you have an example where name!=symbol?

**Comment by ligi** [comment]
the only problem now it gets inconsistent info_url vs nativeCurrency - I would then go with CamelCase everywhere

**Comment by pedrouid** [comment]
> do you have an example where name!=symbol?

Ethereum Mainnet
```json
"nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH"
}
```
