### ISSUE TITLE
Reserve shortname '*'

### ISSUE THREAD

**Issue by danfinlay** [ethereum-lists/chains#734]
I would like to propose reserving the `shortName` of `eoa`, representing an externally owned account chain that is associated with all/no networks.

This would be useful in the case of [EIP-3770](https://github.com/ethereum/EIPs/pull/3770) address validators, so that their logic can be more concrete:

- If the address has a prefix of a network different than the current asset: warn/prevent.
- If the asset has a prefix of the same network as the current asset, show no warning.
- If the receiving address has an `eoa` prefix, no send warning is strongly required from any evm-compatible asset (as the receiving address has expressed its cross-chain ability).

```
{
  "name": "Externally Owned Account",
  "shortName": "eoa",
  "chain": null,
  "network": null,
  "chainId": null,
  "networkId": null,
  "rpc": [],
  "faucets": [],
  "infoURL: null,
  "nativeCurrency": null
}
```

**Comment by danfinlay** [comment]
I'm open to other shortnames, too. Maybe `*`?

**Comment by ligi** [comment]
I am open to reserve a shortname - what I am struggling with is to add it to the dataset like this.
Tend more in direction "*" than EOA as I think it describes more the nature of it.

**Comment by danfinlay** [comment]
Should I fill in more dummy data rather than nulls to preserve strictness? Wouldn’t know what values to add for chainId, etc.

**Comment by ligi** [comment]
No - I think dummy data would also not be nice. Can't we just block this in the CI? Not yet seeing a strong need to have it in the dataset itself.

**Comment by ligi** [comment]
shortName '*' is now blocked
