### ISSUE TITLE
chainlist.org vs chainid.network

### ISSUE THREAD

**Issue by kuzdogan** [ethereum-lists/chains#757]
I've been working with chainId's and using this repo as a reference for chain metadata. However, I come across two chain list `.json`s that seem to be conflicting and have been confusing me:
https://chainid.network/chains.json
https://chainlist.org/chains.json

From what I understand in README, chainid.network is the website of this repository and the chainlist.org is the staging. The contents of chainlist.org seem to be outdated and not to be serving as a staging server. Even if that is the case, I find the domain name chainlist.org confusing as it implies an official chain list and not a staging server. I wasn't aware of this until diving deeper into what's going on.

I suggest changing the staging server name to something like staging.chainid.network and having the contents of chainlist.org and chainid.network the same. There seems to be some clarification needed in this regard.

**Comment by ligi** [comment]
We have no control over chainlist.org or networklist-org.vercel.app - this is done by someone else. You might want to report it to https://github.com/antonnell/networklist-org

**Comment by kuzdogan** [comment]
Then I suppose chainlist.org and networklist-org.vercel.app are neither staging versions nor more up-to-date lists as stated in README.

Also it seems chainid.network does not have a UI but I also see https://chainid.network/ redirects to https://chainlist.org . 

At least on chainid.network's side, it should be made clear these projects are different and this repo serves as the basis.

**Comment by ligi** [comment]
> Then I suppose chainlist.org and networklist-org.vercel.app are neither staging versions nor more up-to-date lists as stated in README.

I think it is correct in the README - chainlist.org has older data - networklist-org.vercel.app  more up to date data. How would you phrase it?

> At least on chainid.network's side, it should be made clear these projects are different and this repo serves as the basis.

how would you do this? I do not really care for the visualization - I only care for the data.

**Comment by kuzdogan** [comment]
Ok now I get it. I see chainlist.org is making use of https://chainid.network/chains.json anyway [in their code](https://github.com/antonnell/networklist-org/blob/25f6542686232f67528a8e3c96b01d5a2b217a71/pages/index.js#L84). My source of confusion has been the https://chainlist.org/chains.json file which was removed in the latest version: [Commit: @8dded17 Remove public chains.json file to avoid confusion.](https://github.com/antonnell/networklist-org/commit/8dded1788ae0cb31f690c10b95c7f99fdb287f09) (so https://networklist-org.vercel.app/chains.json does not exist) but not applied to the production yet. 

Just if chainlist.org and networklist-org.vercel.app are using the same *data* (chains.json) but just the the frontend codes are different (prod. vs staging), I'd change the " a more up-to-date list" part. Correct me if this is not the case.

Anyway, clarification is needed in on [antonnell/networklist-org](https://github.com/antonnell/networklist-org)'s side, at least some description in README as discussed in @8dded17, and I will be bringing it up there.
