### ISSUE TITLE
Inconsistent formating with `title`

### ISSUE THREAD

**Issue by kuzdogan** [ethereum-lists/chains#758]
Looking at the JSON at https://chainid.network/chains.json I noticed the field `title` exists on 6 of the networks. In that case, `title` seem to have the complete name of the network but `name` only the short version. Whereas the `name` field in other networks contain the full name. 

This causes inconsistent network names when using chainid.network to convert chainId's to chain names:
![image](https://user-images.githubusercontent.com/13069972/148955921-54c7bcbb-2951-4888-bfca-0c5b90054d78.png)

### Networks with `title` 
```
    "name": "Arbitrum Rinkeby",
    "title": "Arbitrum Testnet Rinkeby",

    "name": "Kintsugi",
    "title": "Kintsugi merge testnet",

    "name": "Rinkeby",
    "title": "Ethereum Testnet Rinkeby",

    "name": "Görli",
    "title": "Ethereum Testnet Görli",

    "name": "Kovan",
    "title": "Ethereum Testnet Kovan",

    "name": "Optimistic Kovan",
    "title": "Optimistic Ethereum Testnet Kovan",
```

### Other networks' format
```
     // no title field
    "name": "Ethereum Testnet Ropsten",

    "name": "Ethereum Mainnet",

    "name": "Ubiq Network Testnet",
     ... 
```

It is possible to check if the `title` field exist as a workaround. Nevertheless the formatting seemed inconsistent and I was wondering if there was a specific reason behind this.

**Comment by ligi** [comment]
There is a ticket to backfill: #757 

name was just too long for most networks - this is not really a name - this is a title. So introduced title and started to shorten the name for some networks - needs more work to backfil.

**Comment by kuzdogan** [comment]
Thanks. I guess the backfill ticket will be https://github.com/ethereum-lists/chains/issues/723

**Comment by ligi** [comment]
yes - #723 - copy and paste error
