### ISSUE TITLE
chainid.network versus chainlist.org ?

### ISSUE THREAD

**Issue by bumblefudge** [ethereum-lists/chains#787]
The former redirects to the latter but the former is still listed on the repo "about" section on the right sidebar.  Is it deprecated? Feel free to fix nothing and close my issue if nothing is broken, just checking :D

**Comment by ligi** [comment]
chainlist.org is 3rd party but was better than the placeholder that was there at some point so for now a redirect. Might change in the future - still want a site with WalletConnect + static - just no time yet
