### ISSUE TITLE
collision on chainID 1280

### ISSUE THREAD

**Issue by MechAArmA** [ethereum-lists/chains#891]
Hello everyone,

 I create this thread today to start a debate which, possibly, could lead to a solution to this problem that has existed for quite some time.
We created our EVM during 2021 and when we did we used the ID : 1280, ID which to my surprise was already registered on Chainlist  .
 This raises the following question: should there be a prioritization system concerning the attribution of a Chainlist ID according to the creation date of the EVM? 
This would makes more sense and be more fairplay , in my opinion , first come first served 
If any of you have an opinion on the matter, I look forward to your feedbacks !

Thanks,
Mech.

**Comment by ligi** [comment]
When exactly in 2021 was your genesis? Seems the other one started in april:

![image](https://user-images.githubusercontent.com/111600/154339928-c4cc4943-4f9c-4a26-83ef-da9fa492ece2.png)

**Comment by ligi** [comment]
ccIng @f4nzkrys31 as you submitted the halo chain
