### ISSUE TITLE
[New Chain / Network]

### ISSUE THREAD

**Issue by Elizaberh** [ethereum-lists/chains#91]
> Fill out the following to add your chain / network id, OR propose a Pull Request making your edits to the ```_data/chains.json``` file directly

```0x708E1c28d72BBDF1cdC7865c1c6e11bFBdD2968b
{
  "name": "Ethereum Mainnet",
  "shortName": "eth",
  "chain": "ETH",
  "network": "mainnet",
  "chainId": 1,
  "networkId": 1,
  "rpc": ["https://mainnet.infura.io"],
  "faucets": [],
  "infoURL: "https://ethereum.org",
  "nativeCurrency": {"name":"Ether","symbol":"ETH","decimals":18}
}
```

**Comment by ligi** [comment]
we already have mainnet in the list - what am I missing?

**Comment by pedrouid** [comment]
The activity for this Github account seems suspicious. I believe it's a spam bot

**Comment by ligi** [comment]
true - thanks - closing
